### ISSUE TITLE
Future idea - Alternative to CyberConsole?

### ISSUE THREAD

**Issue by DartPower** [yamashi/PerformanceOverhaulCyberpunk#100]
Can you (in near future, for example) write debug/cheat console? 
Reason: CyberConsole is still closed source, but author want to publish to Github, but im dont know when author want to publish.

P.S. And.. i have some ideas & requests: NoClip mode (i don't know, RED Engine supported or not this stuff, but this cheat not have in The Witcher 3 and/or both Console mods)

**Comment by yamashi** [comment]
This is done starting from v1.0
