### ISSUE TITLE
Cyberpunk does not launch at all after installing

### ISSUE THREAD

**Issue by eisenbruch** [yamashi/PerformanceOverhaulCyberpunk#104]
Installed this and the game does not launch at all. If I follow uninstall steps it launches no problem.

**Comment by eisenbruch** [comment]
I converted codex to gog version when I was updating to 1.04. Could that be the issue? How do I repair the exe?

**Comment by PhantomGamers** [comment]
It works fine with the GOG and Steam versions of the game. You won't find support for pirated releases here as it's not a problem with the mod...

**Comment by eisenbruch** [comment]
How can I convert my game into a version that will work with the mod?
