### ISSUE TITLE
Not much happened after I installed. (Slight fps increase but not much.)

### ISSUE THREAD

**Issue by LegendModzYT** [yamashi/PerformanceOverhaulCyberpunk#106]
So I installed this thinking I would get some performance increases, which kinda helped but didn't really increase any fps well somewhat. I am using an i7-7700K paired with a GTX 1060 6GB but am only able to get 30fps on medium and 28-31fps on high which is much better before so thanks for that but I am under the impression that I should be getting 60+ fps yet I'm not, If you could suggest some things to try, I'm open to it.

**Comment by Konnie1989** [comment]
I am still having to play on low with a 1060 6GB and Ryzen 5 3600. My FPS is 35-50. I think that despite the fantastic work Yamashi is doing, the game itself has severe issues that need to be fixed by the Devs.

**Comment by LegendModzYT** [comment]
> I am still having to play on low with a 1060 6GB and Ryzen 5 3600. My FPS is 35-50. I think that despite the fantastic work Yamashi is doing, the game itself has severe issues that need to be fixed by the Devs.

Yea I agree with you, Yamashi did fantastic work, only the Devs of Cyberpunk 2077 need to fix all the bugs and optimise it. Well the good thing is that I haven’t crashed yet, used to crash after the prologue before Stanley’s cutscene thing but now I don’t so yea. I think CD Projekt Red are planning PC updates in January 2021 and Patch 2 in February 2021 which is alright but should have been sooner or even tested more vigorously but then again they were forced to release a clearly unoptimised game which impacted day one reviews.

**Comment by billw1** [comment]
[For your specs 30fps is quite low but 60fps is not expected](https://static.techspot.com/articles-info/2164/bench/1080p_Medium.png). The GTX 1060 is a 4 year old midrange card so I wouldn't expect a whole lot

**Comment by yamashi** [comment]
I would try disabling async compute, it helps with older gpus
