### ISSUE TITLE
Mod was working 24 hours ago. Now it isn't.

### ISSUE THREAD

**Issue by CN53** [yamashi/PerformanceOverhaulCyberpunk#109]
I loaded yamashi's plugin yesterday and it worked great! 90% gpu usage (up from 40%) and 80% cpu usage (up from 50%). For once I was actually enjoying the game because I could play 1440p above 30 frames per second.

A day later, gpu and cpu usage went back to being capped to around 30-50%. Playing Cyberpunk on lowest settings nets me 40fps while playing on the highest settings (minus RTX) nets me 40fps as well. Basically the game reverted to the previous iteration (before I loaded the plugin). 

I've clean installed the plugin and my graphics drivers as well. Log file indicates the plugin is working as intended however in-game it does not appear to be adjusting the memory pool budget. (Other aspects of the plugin, mainly the non-performance improvements are working fine) I have checked my memory_pool_budget file and its all at default values.

Not sure what happened, any insight could prove useful.

EDIT: Just noticed as well, I no longer get the 'Whoa! Cyberpunk 2077 has flatlined' error when closing the game.

**Comment by Benman2785** [comment]
same here

**Comment by Xanoreus** [comment]
I rolled back to a previous version as well. I've had success up to 8.0, anything last this will cause performance drops.

**Comment by yamashi** [comment]
As stated multiple times, it is the user's job to configure the mod, it's not a magic fix, you have to try different settings until you find what works for you.

**Comment by judehunter** [comment]
@yamashi that's a weird response to this issue?

The issue clearly states the mod worked before, but suddenly stopped, as if the game wasn't loading the files.
Moreover, @Xanoreus mentioned the breaking change occurred some time after v0.8.0, presumably v0.8.1 or v0.9.0

Reopen?

**Comment by yamashi** [comment]
They didn't say it worked before a patch and then stopped working so this is not mod related.

**Comment by CN53** [comment]
That's my bad, I was on 0.5.2 and it worked great. Forgot I updated to 0.8.1 later. The issue for me is, unlike @Xanoreus, reverting back to 0.5.2 with a fresh installation did not seem to solve my issue.
