### ISSUE TITLE
SMT Patch, Spectre Patch & Pool Patch failed

### ISSUE THREAD

**Issue by CoLumc** [yamashi/PerformanceOverhaulCyberpunk#11]
Hey,

for me, Spectre, SMT and Pool Patch is not working.
[performance_overhaul.log](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5688354/performance_overhaul.log)

Thank you!

**Comment by yamashi** [comment]
It looks like you modified your executable. 
Repair it if you want to use this mod, it only works on non edited executables.
