### ISSUE TITLE
option to force DLSS?

### ISSUE THREAD

**Issue by elogicuk** [yamashi/PerformanceOverhaulCyberpunk#110]
Im running cyberpunk on linux

i have an RTX 2060 that supports DLSS

but the settings are greyed out, anyway you can force these?

**Comment by elogicuk** [comment]
i tried adding this to the user.ini and it does not work

[DLSS]
Enable = true
EnableMirrorScaling = true
MirrorScaling = -1.000000
Quality = 2
Sharpness = 0.000000

**Comment by johnneijzen** [comment]
just wondering do have integrated gpu on by any chance? 

it seems to be a common issue in the game based on sources:
https://www.nvidia.com/en-us/geforce/forums/geforce-graphics-cards/5/418705/cant-enable-dlss-in-cyberpunk-2077-on-rtx-2060-but/

https://linustechtips.com/topic/1280727-dlss-on-my-rtx-2060-is-not-working-in-any-game-can-anyone-help-me/

**Comment by elogicuk** [comment]
I have no integrated gpu, my cpu is intel i9-9900KF (KF = no on board graphics)

**Comment by R-drg** [comment]
It maybe some driver issue on linux. Can you enable it on other games?

**Comment by skeevy420** [comment]
> 
> 
> It maybe some driver issue on linux. Can you enable it on other games?

This is a Windows issue and effects more than just this game.  For whatever reason some games just don't register that a GPU supports DLSS and will either grey out or won't show the DLSS options.

**Comment by jerbmega** [comment]
Not a Cyberpunk issue. From my understanding, although DLSS is natively supported on Linux, it *only* functions with native Linux games, and not games run through Wine/Proton.
