### ISSUE TITLE
[Feature Request] Option to disable shadows

### ISSUE THREAD

**Issue by nicknitewolf** [yamashi/PerformanceOverhaulCyberpunk#113]
DistantShadows
LocalShadows
ContactShadows

Disabling shadows will help a lot of low end systems to run cyberpunk at a playable state. These options are editable in the game's default settings file but it would be nice if it would be implemented within this patch together

**Comment by XCanG** [comment]
I think you would better to use this mod: https://www.nexusmods.com/cyberpunk2077/mods/183
