### ISSUE TITLE
I don't have plugins folder in bin/x64

### ISSUE THREAD

**Issue by Natsume150** [yamashi/PerformanceOverhaulCyberpunk#117]
as title says, there is no plugins folder, there is ''Cyberpunk2077.exe.plugins'' folder from the zip, after running there game I don't see any difference.

**Comment by Simzy** [comment]
Just drag and drop the files and folder from the zip into the x64 folder, that will make the plugins folder for you.

**Comment by Natsume150** [comment]
> Just drag and drop the files and folder from the zip into the x64 folder, that will make the plugins folder for you.

I did, it makes a folder called ''Cyberpunk2077.exe.plugins'' not ''plugins''  and there is only ''performance_overhaul.dll'' inside it, after running the game and closing, no other file appearing inside it. performance overhaul log file shows this.
![ScreenShot_20201217230420](https://user-images.githubusercontent.com/23087576/102537669-49bbb600-40bc-11eb-9474-c1c7029b869b.png)

**Comment by Simzy** [comment]
clearly you must have done something wrong because there is no file that does that in this mod, https://puu.sh/GYwOa/9b210f44a7.png that is how my folders are including the contents of the zip file

**Comment by Natsume150** [comment]
seems I downloaded the wrong zip, my zip file was saying ''Release-107-0-2-0-1607860050.zip'' I downloaded again from latest release, gonna close the issue, thanks xD
