### ISSUE TITLE
Not an issue, but a request to state current version in the log

### ISSUE THREAD

**Issue by BitGrub** [yamashi/PerformanceOverhaulCyberpunk#118]
Because of how fast this awesome collection of tweaks is updating, it's kind of difficult to keep track of what version I'm currently on, and if there's a newer version available. Also if the mod could generate its own json file (and the release.zip didn't include one), that'd be great, so I wouldn't have to reconfigure it with every update. Thanks!!

**Comment by yamashi** [comment]
It does recreate a json or update it if some settings are missing.
I am including the default config you don't have to replace your current with it if you don't want to.

To keep track of the updates the best course of action would be to look at the wiki.

I am working on a big feature and also have my medical board exam in 3 weeks so I will slow down on updates ^^

**Comment by BitGrub** [comment]
That’s alrigh, appreciate the response. Good luck on your exam 😁
