### ISSUE TITLE
Pedestrians and traffic is gone

### ISSUE THREAD

**Issue by marceloavf** [yamashi/PerformanceOverhaulCyberpunk#122]
Hi, first of all, thanks for this mod.

I'm having a problem that all pedestrians and traffic are gone even with this option disabled and I have never enabled this since it was released.

**Comment by thefunkygibbon** [comment]
yup, it says in the release notes of the hack that if you enable it and save, then all saves from that point onwards will have no peds.  you need to roll back to a prior save (i guess)

**Comment by marceloavf** [comment]
@thefunkygibbon the problem is that I have never enabled it :/

**Comment by strangeowl** [comment]
same here, notice this problem when moving around Japantown. It used to be a lot of people on Joytoys.
So the save is entirely broken?
Never changed the settings before, just download and put the mod in game file path.

**Comment by iffa** [comment]
Yeah noticed the same after installing the latest release, some do seem to still spawn but not a whole lot.

**Comment by yamashi** [comment]
What version was that on and can you send the logs?

**Comment by MescalHeart** [comment]
Update to the latest version and check the config, there was one version where it was enabled by default without config. To be extra sure, delete your old patch files first before copying in the latest version.

**Comment by thefunkygibbon** [comment]
doesn't much help if your last save before that bugged version was many hours worth of gameplay ago though does it?
can you advise on which version it was that was bugged like that so we can tell if we used it?

**Comment by strangeowl** [comment]
> doesn't much help if your last save before that bugged version was many hours worth of gameplay ago though does it?
> can you advise on which version it was that was bugged like that so we can tell if we used it?

Can not provide the exact version because I had update from the very old version. Before I delete the mod, I guess it might be this one  v0.10.0 (fb5e911)

**Comment by marceloavf** [comment]
Any way to get it back without having to find an older save file?

**Comment by thefunkygibbon** [comment]
guess not then seeing as this is now closed 👎

**Comment by marceloavf** [comment]
0.10.0 is from 16 Dec, I'll try to get back to some save before it and see if this problem goes away, but saves seems to be limited in the game...
