### ISSUE TITLE
Version 1.0: pool patch error and console doesn't seem to work

### ISSUE THREAD

**Issue by micdah** [yamashi/PerformanceOverhaulCyberpunk#125]
Just updated from 0.10.0 to 1.0.0 to try out the new console addition, but I cannot get it to work.

When I press "End" I do see a cursor appear, but no window/console anything appears - moving the mouse now only moves the cursor around the screen. Pressing "End" again goes back to normal.

Checking the logs I don't see anything related to console, but I am seeing `Pool patch: error` which was working before.

```
[2020-12-18 19:08:29.523] [info] Computed .text crc: D7E90F30
[2020-12-18 19:08:29.523] [info] 	Resolved to version: 1.04
[2020-12-18 19:08:29.542] [info] 	AMD SMT Patch: success
[2020-12-18 19:08:29.561] [info] 	Spectre patch: success
[2020-12-18 19:08:29.561] [info] 	AVX Patch: skip, cpu has AVX support
[2020-12-18 19:08:29.563] [info] 	Pool patch: error
[2020-12-18 19:08:29.566] [info] 	Virtual Input Patch: success
[2020-12-18 19:08:29.609] [info] 	Start screen patch: success
[2020-12-18 19:08:29.633] [info] 	Hook mouse clip function!
[2020-12-18 19:08:29.812] [info] 	D3D12 hook complete
[2020-12-18 19:08:30.095] [info] 	CPU RAM: 31GB, using 16.0GB, fraction: 0.5
[2020-12-18 19:08:30.161] [info] 	GPU VRAM: 11.0GB, using 11.0GB, fraction: 1.0
```

**Comment by yamashi** [comment]
It is likely that another software that does overlays is conflicting with the console. For example if I use the RivaTunner overlay it doesnt show for me...

**Comment by yamashi** [comment]
The pool error log was just a reversed log, I fixed it in 1.0.1.
Let me know if you find which overlay is preventing the console from showing.

**Comment by BlindedPingu** [comment]
I have same problem with version 1.0.1

Maybe this error message will help
![err](https://user-images.githubusercontent.com/32579213/102648167-13dc0780-4178-11eb-816b-d6aac743365e.png)

**Comment by yamashi** [comment]
This error means your game version is not supported. I will make it so that it doesn't crash ^^

**Comment by yamashi** [comment]
1.0.2 won't display an error anymore but it will not show anything in your case until you fix your exe!

**Comment by micdah** [comment]
Hi @yamashi just to confirm that indeed running MSI Afterburner (which uses RivaTuner) was the cause for the console now showing.

Also after updating to 1.0.2 I don't get the "Pool patch: error" in the logs anymore. 👍 

It's a shame I cannot run MSI Afterburner AND have the console, as I really cannot run without afterburner 😄 It doesn't seem to work as long as RivaTuner is running, even though the OSD it not shown.

**Comment by micdah** [comment]
Hi @yamashi just a FYI, if I disable RivaTuner dependent functionality when launching the game (_using the `Toggle On-Screen Display server blocking` keyboard shortcut in MSI Afterburner_), and then re-enable it ones the game has launched (_and thus your hook also_), then **both** the console and on-screen displays provided by RivaTuner work and co-exist just fine.

Seems a bit of a faff, but nice being able to have both. 😄

**Comment by PhantomGamers** [comment]
@micdah If that works, then perhaps increasing the injection delay in Cyberpunk's RTSS profile would also remedy the problem?
