### ISSUE TITLE
Can't start because d3d12.dll is missing

### ISSUE THREAD

**Issue by sbjcom** [yamashi/PerformanceOverhaulCyberpunk#127]
I am using Windows 7 with an AVX affected CPU and an AMD gfx card. When installing and running your latest code (v1.0.2) on 18DEC, I receive the following error:

Cyberpunk.exe:
"The program can't start because d3d12.dll is missing from your computer."

And then:

ASI Loader:
"Unable to load cyber_engine_tweaks.asi. Error: 126"

**Comment by ApocArkhesir** [comment]
d3d12.dll is part of DirectX 12, which is not supported on Windows 7. You would need to upgrade to Windows 10 to run it.

**Comment by yamashi** [comment]
Yes Windows 7 users need to upgrade. Microsoft dropped support for Windows 7, I am not gonna bother with it, it's 11 years old.

**Comment by sbjcom** [comment]
I am well aware that DX12 is not on Win7 ... I was just reporting a problem that was not mentioned in the wiki nor was found in the list issues. If Win 7 will not be supported, then please make a note of that on the wiki to save us poor Win 7 user's some time. ;)
