### ISSUE TITLE
Use the actual GPU's VRAM size

### ISSUE THREAD

**Issue by yamashi** [yamashi/PerformanceOverhaulCyberpunk#13]
Currently the PoolCPU is using the real RAM size of the machine but not the GPU (because windows doesn't expose a simple way to do this).

It would be a lot better to use the actual GPU's memory size, see: https://github.com/yamashi/PerformanceOverhaulCyberpunk/blob/master/cyberpunk_patch/src/pool_patch.cpp#L26

**Comment by grepwood** [comment]
What about https://github.com/yamashi/PerformanceOverhaulCyberpunk/issues/3#issuecomment-744179623 ?

**Comment by yamashi** [comment]
This would be a bit dangerous for lower end configs I think

**Comment by CookiePLMonster** [comment]
Are you sure those configs do anything in the first place, though?

**Comment by yamashi** [comment]
They are indeed used in the engine and some players report improvements, I don't see any personally but it doesn't cost much...

**Comment by asafteirobert** [comment]
I realize reading reading GPU VRAM is always tricky, so it could be a config option.

**Comment by yamashi** [comment]
Fixed in v0.5.2
