### ISSUE TITLE
Playstation 5 controller support broken.

### ISSUE THREAD

**Issue by serioussam909** [yamashi/PerformanceOverhaulCyberpunk#130]
The latest release breaks the PS5 controller support.

Rolled back to this one where it still works.
https://github.com/yamashi/PerformanceOverhaulCyberpunk/releases/tag/v0.10.0

**Comment by Sleetzer** [comment]
> The latest release breaks the PS5 controller support.
> 
> Rolled back to this one where it still works.
> https://github.com/yamashi/PerformanceOverhaulCyberpunk/releases/tag/v0.10.0

Also having this issue with the DS4 Controller for PS4

**Comment by yamashi** [comment]
Note for potential contributions : v1.0.0 introduced the bug, bisecting the commits from 0.10.x to 1.0 is likely the best course of action.
Could very well be imgui related as the wndproc hook doesn't forward events handled by imgui.
