### ISSUE TITLE
Windows 7 support? 

### ISSUE THREAD

**Issue by seighail3** [yamashi/PerformanceOverhaulCyberpunk#131]
I have z170 motherboard and 

GTX1070
i7 6700k 
24gb

and I get 30fps and I cant use this mod .... 

mmh I bought this game for full price pre order :( I dont wanna buy a new ssd just to boot out of bloateddows 10

**Comment by PhantomGamers** [comment]
Microsoft doesn't even support Windows 7 anymore, why should anyone else? Just upgrade...
