### ISSUE TITLE
Changing the "memory_pool_budgets.csv" file has no effect on the game, as confirmed by CDPR support.

### ISSUE THREAD

**Issue by xezno** [yamashi/PerformanceOverhaulCyberpunk#132]
Hey,

First off, thanks for the mod. Many of the tweaks here have helped greatly improve the game's performance!
This is less of a bug report / issue, and more just a general notice that the `memory_pool_budget.cvs` file apparently has no purpose within the final game - any improvement gains are supposedly placebo - and is just a leftover from debugging. This has been confirmed by CD Projekt Red support as shown in [this Reddit thread](https://www.reddit.com/r/cyberpunkgame/comments/kfrs5m/confirmed_by_cdpr_tech_support_team_memory_pool/):

![image](https://user-images.githubusercontent.com/12881812/102668703-7cc97c80-4184-11eb-9440-6517229a46f1.png)

Obviously I can't confirm this 100%, since I haven't done any benchmarking or testing myself, but since it's coming straight from the source I thought it'd be something of note.

**Comment by yamashi** [comment]
As a future doctor I can vouch for the placebo effect, I had my fair share of doubts regarding this "fix" but if it makes some people happy, it doesn't cost anything ;)

**Comment by xezno** [comment]
Ok - just be aware that [as of patch 1.05](https://www.cyberpunk.net/en/news/37166/hotfix-1-05) the file has been removed anyway.
