### ISSUE TITLE
Change console toggle key

### ISSUE THREAD

**Issue by yamashi** [yamashi/PerformanceOverhaulCyberpunk#133]
End apparently conflicts with Reshade, we should use another default and it would be great to be able to configure the key.

**Comment by FelesNoctis** [comment]
Configuring the key would be a definite plus. I had to reconfigure Reshade to use a different key combination because I have a 75% keyboard, and I'm missing most of the navigation cluster (home, end, etc).

**Comment by travisnewman** [comment]
Tilde is always the console key in basically every other game I've played that has one, and the one that the CyberConsole mod on nexus uses as well.

But yeah, configurable would be great.
