### ISSUE TITLE
Console doesn't work :(

### ISSUE THREAD

**Issue by TrophyHunterPL** [yamashi/PerformanceOverhaulCyberpunk#135]
Pressing End key brings mouse cursor but do not show the console, no matter the view: windowed, borderless or fullscreen.

**Comment by yamashi** [comment]
Please give details on your setup. OS, mods installed, overlays?

**Comment by ExKnoll** [comment]
Having the same problem.  Mine comes up but its a 40 x 40 pixel window that can't display anything much.  Running:
@1080p
Win 10
Only your mod
No GOG overlay
Fresh and clean system with all updates installed and the newest version of your code.

Great work btw, thank you.

**Comment by TrophyHunterPL** [comment]
Windows 10 64bit 20H2, R7 3800X, RTX 3080, no mods only this one.

And the culprit is MSI Afterburner overlay. When I go to the game as normal with those overlays nothing happens. When I restart my computer, turn of msi afterburner and riva tuner, start the game, the console shows up! Then when I minimize the game, start those overlays, the console still shows up. But in the scenario when I start the game with those overlays, minimize and shut down those overlays, the console doesn't show up.

I hope this helps, you are doing gods work!

**Comment by yamashi** [comment]
Yes I have the same issue on my machine you can't imagine how frustrating it was to wonder for hours why nothing was working and then disabling rivatuner was all it took...
I am probably going to try to fix this but can't promise results or a time frame!
Glad you got ir working!
