### ISSUE TITLE
Memory pools - actually not used by game (CDPRED Hotfix 1.05 patch notes)

### ISSUE THREAD

**Issue by miartan** [yamashi/PerformanceOverhaulCyberpunk#139]
> Removed the memory_pool_budgets.csv file. which was not connected with the final version of the game and had no influence on it (it was a leftover file used during the development to estimate memory usage. It had no effect on how much memory was actually allocated). Perceived performance increase after editing the file may have been related to restarting the game.

https://www.cyberpunk.net/en/news/37166/hotfix-1-05

**Comment by FelesNoctis** [comment]
That's stating the csv file wasn't used by the game. This tool is modifying the game's memory management directly, it's a bit different.

However, there are AMD SMT and AVX changes that will need to be addressed.

**Comment by miartan** [comment]
I made multiple benchmarks using tool, manually editing the mentioned .csv values or leaving it on default.
Using the streaming tests from the unlocked dev menu and didn't measure any significant performance difference whatsoever.

**Comment by FelesNoctis** [comment]
Memory allocation and management is also heavily reliant on your hardware. It's very possible that your configuration doesn't need that particular optimization. It'll vary from system to system.

I can confirm on my end that while my game's performance wasn't dramatically affected, I noticed significantly less memory-related issues (such as textures not loading properly, meshes being invisible, pop-in flicker, etc) after this was installed.

**Comment by rashil2000** [comment]
>https://www.cyberpunk.net/en/news/37166/hotfix-1-05

@yamashi Since this patch includes fixes for SMT and AVX, wouldn't there be conflicts if we use this repo along with 1.05 patch?

**Comment by yamashi** [comment]
We have to wait for the patch to drop to know what the patch needs to do and not not do ^^

**Comment by pchristod** [comment]
To add to this: From the Changelog it reads they added SMT Optimization only for 4 and 6 core processors while everything else remains unchanged. However i received a huge gain in fps with this performance mod collection (from the very early versions) on my 3700x (8 core) which leads me to the conclusion this will still be relevant with patch 1.05. But lets see.

**Comment by Saibamen** [comment]
>We have to wait for the patch to drop to know what the patch needs to do and not not do ^^

So please reopen this ticket...

**Comment by Saibamen** [comment]
1.05 is not live. Please reopen this issue and remove patch
