### ISSUE TITLE
Instructions page lists a path that's not real

### ISSUE THREAD

**Issue by Hellreaver** [yamashi/PerformanceOverhaulCyberpunk#14]
This page
https://github.com/yamashi/PerformanceOverhaulCyberpunk/wiki
Lists path
`<cyberpunk install path>/bin/x64/performance_overhaul/performance_overhaul.log`
But that's not a path in any directory spawned from this download, nor is the log file.

**Comment by yamashi** [comment]
Meaning you didn't install it properly ^^

**Comment by Hellreaver** [comment]
> Meaning you didn't install it properly ^^

It's literally not in any of the directories in the download, is it supposed to be generated after the game starts for the first time?

**Comment by yamashi** [comment]
Yes after you launch the game it will be generated.
