### ISSUE TITLE
Latest version broke the renderer entirely

### ISSUE THREAD

**Issue by ipoopedmypantsuups** [yamashi/PerformanceOverhaulCyberpunk#142]
Not sure what happened with the newest update, but launching the game now just shows a frozen screen. Audio continues in the background but screen does not update. 

This is me in the main menu, with the console open. I can still hear the game, but nothing on-screen changes. If I alt+tab then go back into the game, it updates, but only for the last frame. 
![image](https://user-images.githubusercontent.com/73392805/102684735-47835580-41a9-11eb-87ad-e0dc86abc2ee.png)
Windows 10, 20H2, i7, Nvidia 980 GTX, 64 GB of Ram. 

Any support?

> [2020-12-19 03:23:28.550] [info] Computed .text crc: D7E90F30
> [2020-12-19 03:23:28.550] [info] 	Resolved to version: 1.04
> [2020-12-19 03:23:28.578] [info] 	AMD SMT Patch: success
> [2020-12-19 03:23:28.604] [info] 	Spectre patch: success
> [2020-12-19 03:23:28.604] [info] 	AVX Patch: skip, cpu has AVX support
> [2020-12-19 03:23:28.606] [info] 	Pool patch: success
> [2020-12-19 03:23:28.610] [info] 	Virtual Input Patch: success
> [2020-12-19 03:23:28.669] [info] 	Start screen patch: success
> [2020-12-19 03:23:28.707] [info] 	Hook mouse clip function!
> [2020-12-19 03:23:28.957] [info] 	D3D12 hook complete
> [2020-12-19 03:23:29.203] [info] 	CPU RAM: 63GB, using 32.0GB, fraction: 0.5
> [2020-12-19 03:23:29.308] [info] 	GPU VRAM: 4.0GB, using 4.0GB, fraction: 1.0
>

**Comment by ipoopedmypantsuups** [comment]
Update: I have seemed to allocate it to the console being enabled. Disabling it to false fixes it, for some odd reason.
Clarification: I set every setting to false, but console set to true, and it only happens when console=true.

**Comment by yamashi** [comment]
The renderer hook is disabled when the console is set to false. I sadly can't debug this kind of issue...

**Comment by ipoopedmypantsuups** [comment]
> 
> 
> The renderer hook is disabled when the console is set to false. I sadly can't debug this kind of issue...

What? ......Going back to the previous version, I can play the game with console=true just fine, but the problem is the console window is blank and I can't type anything...
![image](https://user-images.githubusercontent.com/73392805/102685332-e742e280-41ad-11eb-980c-d01903a7c808.png)

**Comment by ipoopedmypantsuups** [comment]
Dev, help please...

**Comment by yamashi** [comment]
Blank window means the game version is not recognized, look at the logs.
