### ISSUE TITLE
memory_pool_budgets.csv never affected performance and thus is redundant

### ISSUE THREAD

**Issue by HazzyDevil** [yamashi/PerformanceOverhaulCyberpunk#143]
>Removed the memory_pool_budgets.csv file. which was not connected with the final version of the game and had no influence on it (it was a leftover file used during the development to estimate memory usage. It had no effect on how much memory was actually allocated). Perceived performance increase after editing the file may have been related to restarting the game.

Changing the cpu and gpu pool memory should be removed since it doesn't do anything and the .csv file is going to be removed once patch 1.05 comes to PC.

**Comment by AusHick** [comment]
#139
