### ISSUE TITLE
HOTFIX 1.05

### ISSUE THREAD

**Issue by TheOne320** [yamashi/PerformanceOverhaulCyberpunk#144]
> [AMD SMT] Optimized default core/thread utilization for 4-core and 6-core AMD Ryzen(tm) processors. 8-core, 12-core and 16-core processors remain unchanged and behaving as intended. This change was implemented in cooperation with AMD and based on tests on both sides indicating that performance improvement occurs only on CPUs with 6 cores and less.
> 
> Fixed an issue with the way Raw Input is collected.
> 
> Removed the use of AVX instruction set thus fixing crashes occurring at the end of the Prologue on processors not supporting AVX.
> 
> Removed debug console to prevent functions that could lead to crashes or blocked quests. This doesn't mean we don't want to support the modding community. Stay tuned for more info on that.
> 
> 
> Removed the memory_pool_budgets.csv file. which was not connected with the final version of the game and had no influence on it (it was a leftover file used during the development to estimate memory usage. It had no effect on how much memory was actually allocated). Perceived performance increase after editing the file may have been related to restarting the game.

So, most of the features are now in official?

**Comment by yamashi** [comment]
Pretty much

**Comment by cglmrfreeman** [comment]
I apologize for the late comment in this thread, but in the notes stated above it states `removed debug console` and I wish to know if this feature was _actually removed_ or can the same console prior to 1.05 be enabled still by using CyberEngineTweaks along with the current hofix as of this post?

**Comment by WSSDude420** [comment]
Original game console was completely nuked from the game. What CET offers is rrplacement of sorts, but it is not the same.

**Comment by cglmrfreeman** [comment]
Gotcha, thank you for the clarification. I still have 1.04 backed up, so I should theoretically be able to use an old CyberENgineTweaks release to access that, right? I understand that I won't have support for that version, however.
