### ISSUE TITLE
HOTFIX 1.05? Good or Bad? Heads up!!!

### ISSUE THREAD

**Issue by lrhinehart0724** [yamashi/PerformanceOverhaulCyberpunk#146]
HOTFIX 1.05
https://www.cyberpunk.net/en/news/37166/hotfix-1-05
PC-specific
Allot of fixes already fixed by you guys!! But this one caught my eye! Maybe nothing to worry about but thought I would mention it.
_"Removed debug console to prevent functions that could lead to crashes or blocked quests. This doesn't mean we don't want to support the modding community. Stay tuned for more info on that."_

**Comment by ipoopedmypantsuups** [comment]
When is this getting released? Is it Steam-only? Checked GOG and nothing yet. Hellooo???

**Comment by spenderniere** [comment]
the script isnt nessesary with the new patch:

"Removed the memory_pool_budgets.csv file. which was not connected with the final version of the game and had no influence on it (it was a leftover file used during the development to estimate memory usage. It had no effect on how much memory was actually allocated). Perceived performance increase after editing the file may have been related to restarting the game."

"[AMD SMT] Optimized default core/thread utilization for 4-core and 6-core AMD Ryzen(tm) processors. 8-core, 12-core and 16-core processors remain unchanged and behaving as intended. This change was implemented in cooperation with AMD and based on tests on both sides indicating that performance improvement occurs only on CPUs with 6 cores and less."

"Removed the use of AVX instruction set thus fixing crashes occurring at the end of the Prologue on processors not supporting AVX."

**Comment by Reonu** [comment]
They say that 8+ core AMD CPUs are already "working as intended". So for my 5800X I'll still need this mod. I hope it gets updated to support 1.05!

**Comment by striker890** [comment]
> the script isnt nessesary with the new patch:

That's not true. AMD SMT improvements clearly bring huge performance increase and more consisten frame times even on 8 core cpu's. I saw up to 20% increase in 1% low performance on the R7 3800X

**Comment by pchristod** [comment]
Don't know how they can oversee this, but I too clearly had quite a huge performance increase with this mod and I'n on an 8 core 3700x. So yes, I think its still needed, but we'll see.

**Comment by MG4vQIs7Fv** [comment]
> "Removed the memory_pool_budgets.csv file. which was not connected with the final version of the game and had no influence on it (it was a leftover file used during the development to estimate memory usage. It had no effect on how much memory was actually allocated). Perceived performance increase after editing the file may have been related to restarting the game."

This is an obvious lie. I tested this on a freshly restarted game both Before and After the file was edited.

I will be holding off on updating. They seem hellbend to destroy again what the modders fixed about this game.

**Comment by spenderniere** [comment]
> Don't know how they can oversee this, but I too clearly had quite a huge performance increase with this mod and I'n on an 8 core 3700x. So yes, I think its still needed, but we'll see.

I have a 3700x and  a 5700xt and have no performance increase. use capeframe and test it  and show it.

![image](https://user-images.githubusercontent.com/38881872/102691470-1fc5d900-420d-11eb-84e1-2876ffb49f34.png)

**Comment by ipoopedmypantsuups** [comment]
On top of removing an obvious fix and removing debug console permanently this time, I think I'll stick with 1.0.4.

**Comment by amnesia** [comment]
> > Don't know how they can oversee this, but I too clearly had quite a huge performance increase with this mod and I'n on an 8 core 3700x. So yes, I think its still needed, but we'll see.
> 
> I have a 3700x and a 5700xt and have no performance increase. use capeframe and test it and show it.
> 
> ![image](https://user-images.githubusercontent.com/38881872/102691470-1fc5d900-420d-11eb-84e1-2876ffb49f34.png)

The game was unplayable for me before the fix. Microstuttering and FPS drops. After applying the fix (I did it manually on day one), no more problems, I have 80+ hours of buttery smooth playtime now. If I put the original exe back, stuttery mess again. 3700x and 2070S. Without the fix, core utilization is very low, around 35-45%, with the fix, it's 75-85%.

I really don't understand what CDPR is doing right now, but it sure looks like their main goal is to destroy the reputation, as fast as possible.

**Comment by spenderniere** [comment]
> > > Don't know how they can oversee this, but I too clearly had quite a huge performance increase with this mod and I'n on an 8 core 3700x. So yes, I think its still needed, but we'll see.
> > 
> > 
> > I have a 3700x and a 5700xt and have no performance increase. use capeframe and test it and show it.
> > ![image](https://user-images.githubusercontent.com/38881872/102691470-1fc5d900-420d-11eb-84e1-2876ffb49f34.png)
> 
> The game was unplayable for me before the fix. Microstuttering and FPS drops. After applying the fix (I did it manually on day one), no more problems, I have 80+ hours of buttery smooth playtime now. If I put the original exe back, stuttery mess again. 3700x and 2070S. Without the fix, core utilization is very low, around 35-45%, with the fix, it's 75-85%.
> 
> I really don't understand what CDPR is doing right now, but it sure looks like their main goal is to destroy the reputation, as fast as possible.

show it. use https://www.capframex.com/

**Comment by pchristod** [comment]
@spenderniere: Dont need to test it to be honest, I see it via the fps monitor in game.

**Comment by emoose** [comment]
Process monitor does show that memory_pool_budgets.csv is being read by the game at least:

![cp2077](https://user-images.githubusercontent.com/1755499/102692694-eee5a400-420c-11eb-88e9-8bb98d12509e.png)

The values are actually parsed and handled too, this project even has code that hooks into that and increases the numbers it reads.

What isn't known is what happens with those numbers, people reported changing them to 0 and other crazy values with no bad effect, there could have always been a minimum/maximum set for them though, and a default for invalid values.

**Comment by NielsGx** [comment]
I'm hard gpu bottlenecked (ryzen 7 3700x, gtx 1060 6gb)
And all that smt thing didn't even increased my fps by one.

I benchamerked in the same spot, while moving, and checking npc count.

It might be doing smth for cpu bound people, hard to say
