### ISSUE TITLE
Ryzen 5900X SMT on vs off hitching issue

### ISSUE THREAD

**Issue by chronicblondiee** [yamashi/PerformanceOverhaulCyberpunk#148]
I have been testing SMT on vs off for cyberpunk i have seen some people have great gains with it enabled vs with it disabled,

But i also heard that there was some negative scaling with higher core count ryzen cpus,

So i decided to put together some test runs to help you visualize some performance numbers

What I see at a glance is the all physical are loaded to an all core of 4.5 GHz for the most part when in cyberpunk but the games usage sits about 30% with it SMT fix off but with it on I see a decent increase to about 40/50% usage but sometimes i see some hitching frame rate seems to be largely the same as before this is running the latest version of the mod,

The interesting thing about it was the hitching seemed to be caused by a sudden drop in clock speed on the CPU im not sure what causes this issue but it seemed to happen weather SMT Patch was on or off but seemed to be a little more frequent with it enabled,

The CPU isn't trotting either it drop is instant and goes back to normal makes me think so sort of sleep function is happening in game?

 
I have some HW info logs here if you want to take a look for yourself iv attached them
[hw-logs.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5719499/hw-logs.zip)

**Comment by NielsGx** [comment]
Use the high performance power plan.

It helps for people who are cpu bound.

If you are GPU bound, like nearly everyone, you won't see any real difference.

**Comment by chronicblondiee** [comment]
Well I'm running rx6800 gpu and 5900x cpu but it looks to be gpu bound at about 98% on gpu usage

I doubt enabling the high performance power plan will make much difference but maybe it will force the cpu to keep the clocks more consistent I will try it and report back

**Comment by NielsGx** [comment]
Update your chipset or the thing related to your cpu, on the motherboard. It adds AMD ryzen specific power plan. Dunno if it change a lot
