### ISSUE TITLE
Сan not write anything to the console

### ISSUE THREAD

**Issue by Dead4W** [yamashi/PerformanceOverhaulCyberpunk#151]
Console window open successfully and i can move him, but cant write commands

**Comment by hypoflex** [comment]
https://www.cyberpunk.net/en/news/37166/hotfix-1-05

> Removed debug console to prevent functions that could lead to crashes or blocked quests. This doesn't mean we don't want to support the modding community. Stay tuned for more info on that.

debug menu is useless as of today's patch. stay tuned
