### ISSUE TITLE
1.05 thread

### ISSUE THREAD

**Issue by yamashi** [yamashi/PerformanceOverhaulCyberpunk#153]
Please do not open issues for 1.05, the mod will be updated soon, no need to panic, the game should just run normally with the plugin still installed.

**Comment by ViniciusReinas** [comment]
Thank you for continuing to work on the patch!

**Comment by ipoopedmypantsuups** [comment]
Thank you so much for your hard work, it's heavily appreciated! ^^

**Comment by spitfire** [comment]
> Please do not open issues for 1.05, the mod will be updated soon, no need to panic, the game should just run normally with the plugin still installed.

It does, but they didn't seem to fix the AMD SMT issue like they thought they did. Half of the cores unused on my 3900x, haven't really experienced any slowdowns (yet).
Did the RAM/VRAM resources fix really do anything? (they said the csv file didn't really do anything)

**Comment by popcornAC** [comment]
SMT was not supposed be enabled for more than 6core btw ^

**Comment by LittleZen** [comment]
> > Please do not open issues for 1.05, the mod will be updated soon, no need to panic, the game should just run normally with the plugin still installed.
> 
> It does, but they didn't seem to fix the AMD SMT issue like they thought they did. Half of the cores unused on my 3900x, haven't really experienced any slowdowns (yet).
> Did the RAM/VRAM resources fix really do anything? (they said the csv file didn't really do anything)

as @popcornAC  said, if you read the patchnote, they said the patch will not support processor with more than 6 core ... you have yamashi for that 😂😂😂

**Comment by cobrabr** [comment]
FYI, right now it seems the only thing working is the `Start screen patch`. Everything else shows as failed in the log:

```
[2020-12-19 19:06:14.658] [info] Computed .text crc: 20F87F01
[2020-12-19 19:06:14.659] [error] 	Unknown version, please update the mod
[2020-12-19 19:06:14.705] [warning] 	AMD SMT Patch: failed
[2020-12-19 19:06:14.705] [warning] 	Spectre patch: failed, unknown version
[2020-12-19 19:06:14.705] [info] 	AVX Patch: skip, cpu has AVX support
[2020-12-19 19:06:14.807] [info] 	Pool patch: failed
[2020-12-19 19:06:14.849] [warning] 	Virtual Input Patch: failed
[2020-12-19 19:06:14.929] [info] 	Start screen patch: success
```

**Comment by spitfire** [comment]
> > > Please do not open issues for 1.05, the mod will be updated soon, no need to panic, the game should just run normally with the plugin still installed.
> > 
> > 
> > It does, but they didn't seem to fix the AMD SMT issue like they thought they did. Half of the cores unused on my 3900x, haven't really experienced any slowdowns (yet).
> > Did the RAM/VRAM resources fix really do anything? (they said the csv file didn't really do anything)
> 
> as @popcornAC said, if you read the patchnote, they said the patch will not support processor with more than 6 core ... you have yamashi for that 😂😂😂

As far as I understand, they said the problem does not affect AMD CPUs with more than 6 cores, not that they will not fix it. Haven't seen any slowdowns (yet), and the "patch" had not been updated (yet) (not that I expected it to be updated so soon).

**Comment by yamashi** [comment]
v1.1.0 is now working fine for 1.05, enjoy!

**Comment by NielsGx** [comment]
TBH you want only physical cores to be used and not the logical threads.
Especially when you have 8 ohysical cores or more. Way enough for thr games, and physical cores are better than virtual logicsl threads..
