### ISSUE TITLE
CDPR / AMD maybe mistaken about SMT. 

### ISSUE THREAD

**Issue by PixelShake** [yamashi/PerformanceOverhaulCyberpunk#157]
Hey, 
I create performance videos for a graphics card manufacture and so I've been testing various tweaks and fixes to Cyberpunk 2077. Originally I was testing the HEX edit to the Cyberpunk.exe to see how SMT on vs off compared on the Ryzen 7 5800x CPU. My findings were that whilst there where some benefits when under an extreme CPU bottleneck, generally performance would be worse to the tune of around 10-20%. However, it's worth noting that despite the lower frame rate, frame times were greatly improved and the game overall felt better.

This lead me onto this Performance Overhaul. 
Having compared this SMT fix vs the HEX editor, I found that the Performance Overhaul mod offered much the benefits, without any of the downsides. Peak performance was a 1:1 with the game without the fix and yet we had the benefits of smoother frame times and increased performance under a CPU bottleneck. 

Since 1.05 of Cyberpunk, the ability to use this Performance Overhaul has gone. This means that performance on certain higher end AMD CPUs is now worse than it was in 1.04 with this patch applied. Obviously, I have no idea how this patch differed from the HEX edited version of the fix, however, it would be awesome if it would be possible to have it updated to work with 1.05 as I honestly believe that CDPR and AMD must have been testing the HEX edited version of the fix to come up with their conclusions.

**Comment by rigred** [comment]
Thread that is of value
With regards to how SMT affects performance on Zen1 and Zen1+ (1700/2700)
https://twitter.com/CapFrameX/status/1339937752234795008

Data is from me. 

Scroll up on this one:
https://twitter.com/0xCats/status/1338608536029425664
