### ISSUE TITLE
Updated SMT AOB

### ISSUE THREAD

**Issue by sansvila** [yamashi/PerformanceOverhaulCyberpunk#158]
I updated the pattern

New: 75 2D 33 C9 B8 01 00 00 00 0F A2 8B C8 C1 F9 08
Replace first byte(75) with EB

I've performed a simple test with my Ryzen 2700x 8 core/8 thread

Game version 1.05
Game set at 1024x768 on low preset in order to bottleneck the gpu

Original:
    GPU%: 60-65
    CPU%: 40-50
    FPS    : 95-100

SMT Patched:
    GPU%: 60-65
    CPU%: 70-80
    FPS    : 90-95

In other words, this patch actually lowers performance by about 5 fps while substantially increasing cpu usage, on my 2700x

**Comment by PixelShake** [comment]
I've done multiple tests with the HEX edited version of the patch vs that contained within this Performance Overhaul. For some reason, where's the HEX edited SMT fix does indeed hurt peak performance, the Performance Overhaul does not. 

The Performance Overhaul fix matches the frame rate of the game without an SMT fix when GPU bound whilst at the same time as having additional performance whilst under a CPU bottleneck. In contrast, the HEX editor harms performance when GPU bound but still benefits when under a CPU bottleneck. 

I'd advise that everybody avoid these HEX edited SMT fixes UNLESS you're constantly CPU bottlenecked (1000 series ryzen at this point)

**Comment by PerfectOua** [comment]
> I've done multiple tests with the HEX edited version of the patch vs that contained within this Performance Overhaul. For some reason, where's the HEX edited SMT fix does indeed hurt peak performance, the Performance Overhaul does not.
> 
> The Performance Overhaul fix matches the frame rate of the game without an SMT fix when GPU bound whilst at the same time as having additional performance whilst under a CPU bottleneck. In contrast, the HEX editor harms performance when GPU bound but still benefits when under a CPU bottleneck.
> 
> I'd advise that everybody avoid these HEX edited SMT fixes UNLESS you're constantly CPU bottlenecked (1000 series ryzen at this point)

So you advise to use this SMT fix on my Ryzen 1600 af 3.75 GHz + 1080 ti with undervolting on patch 1.05?

**Comment by PixelShake** [comment]
EDIT: You don't need to use the SMT fix as CDPR has automatically added the fix itself to Ryzen CPUs that have less than 8 physical cores (you have 6) so basically the SMT fix is active for you by default in 1.05

IGNORE BELOW
_Providing that you're not still GPU bottlenecked, yes... 
Basically, if you're playing on let's say HIGH settings at 1080p yes. If you're maxing out the GPU completely then no. on a 1080ti at 1440p, I'd prob stay avoid the SMT fix. 

Personally, I'd recommend that you go into game and check your performance / framerate in a spot that you find to be particularly demanding and save the view by saving the game. - Then make a copy of your original cyberpunk.exe and then edit the original using the HEX edit. Go back into game, load that view and if performance is better OR the same, stick with SMT. If performance is worse. Don't use the fix. 

Sorry I know it's complicated but every system is different._
