### ISSUE TITLE
keybinding lost with 1.05

### ISSUE THREAD

**Issue by shemerk** [yamashi/PerformanceOverhaulCyberpunk#166]
I've downloaded and applied the latest version, but all the extra keybind settings are missing.
help?

**Comment by hulovexu1314** [comment]
What button are you binding？

**Comment by shemerk** [comment]
F mostly - the entry to customize it is missing after the  1.05 patch

**Comment by yamashi** [comment]
This is a game bug

**Comment by shemerk** [comment]
Meaning it works for other people?
