### ISSUE TITLE
Opening a console on 1.05 with "~" causes crash to desktop

### ISSUE THREAD

**Issue by DominiX32** [yamashi/PerformanceOverhaulCyberpunk#167]
I have Cyberpunk 2077 v1.05 + Performance Overhaul Cyberpunk + ReShade installed (nothing fancy)

Right now hitting "~" key causes instant crash to desktop, the worst part is it's close to ESC key so it's easy to misclick.
Disabled it in "config.json", right now no crashes.

I will actively respond and provide any necessary info or files if needed

Edit: Learned from project's wiki that configuration is in "config.json" file not "global.ini"

**Comment by hulovexu1314** [comment]
Try to disable ReShade try！

**Comment by yamashi** [comment]
ReShade + this mod doesn't work, no idea when I will be able to look into it.
