### ISSUE TITLE
Save Game Locator and backup

### ISSUE THREAD

**Issue by andregm3** [yamashi/PerformanceOverhaulCyberpunk#170]
Please add save game locator and autobackup I can't find my save game folder

**Comment by hulovexu1314** [comment]
C:\Users\(UserName)\Saved Games\CD Projekt Red\Cyberpunk 2077

**Comment by andregm3** [comment]
mine it's not there, I installed my games on D: Steamapp folder not on C:

**Comment by Dplanton** [comment]
> mine it's not there, I installed my games on D: Steamapp folder not on C:

then you've made some mistake or aren't on windows because that is the location.
