### ISSUE TITLE
Controller stopped working after recent update

### ISSUE THREAD

**Issue by Miss-Corruption** [yamashi/PerformanceOverhaulCyberpunk#174]
Ever since the virtual input (or the console, I'm not sure which version specifically caused this) was added to the patches my Controller (a Horipad) stopped working. Previously I would launch the game through Steam to get the controller recognized. However, if I attempt to do this now my controller would stay unrecognized and no input would be accepted.

**Comment by elogicuk** [comment]
Please fix steam controller support in 1.5 thank you!

**Comment by EricAzure** [comment]
My PS5 controller also stopped working, had to disable steam controller input and use DS4win.
