### ISSUE TITLE
[crash] Incompatibility with Reshade - Console

### ISSUE THREAD

**Issue by bad1dea** [yamashi/PerformanceOverhaulCyberpunk#176]
Crashes when attempting to show the Console when Reshade is installed.

Reshade 4.8.2 installed.
Pressing Console Key to bring up Console - @ Menu / In Game / Etc - results in CTD.

Attached are two crash dumps.

[Cyberpunk2077-20201220-021423-19952-12876.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5721120/Cyberpunk2077-20201220-021423-19952-12876.zip)

**Comment by DominiX32** [comment]
I posted this issue today too, even @yamashi answered me.
Apparently he has this issue on his mind, but there are more important features.

https://github.com/yamashi/PerformanceOverhaulCyberpunk/issues/167

**Comment by bad1dea** [comment]
Oops!

Thanks, please link this @yamashi to other issue when you can.

Thanks! Hopefully more crash logs will help him, I assume his console window hooks the same way reshades console does, since the windows look similar.
