### ISSUE TITLE
Console Command guide

### ISSUE THREAD

**Issue by devilman198** [yamashi/PerformanceOverhaulCyberpunk#178]
is it any guide how to operate console? 

like how to add item, remove item and use other cheats. thanks btw for the mods! love it

**Comment by leon-n** [comment]
https://www.pcgamer.com/cyberpunk-2077-cheats-pc/

perhaps

**Comment by liquidph34r** [comment]
That doesn't work, get some error about indexing "player", when trying the money cheat.

**Comment by ydeng11** [comment]
https://github.com/yamashi/PerformanceOverhaulCyberpunk/wiki/Console

**Comment by virgil-av** [comment]
Using: Game.AddToInventory

returns: 

Error: Function 'Game.AddToInventory' not found or is not a global.

Most likely this does not work in 1.05

**Comment by yamashi** [comment]
It does.

**Comment by Vishal-Ramanlal** [comment]
Could you give an example of how it would be used. I.e adding the buzzsaw

**Comment by yamashi** [comment]
There is an example in the wiki.

**Comment by Vishal-Ramanlal** [comment]
Just says Game.AddToInventory("ItemName", 1), when i do Game.AddToInventory(Preset_Pulsar_Buzzsaw, 1) nothing happens

**Comment by yamashi** [comment]
note the quotes

**Comment by virgil-av** [comment]
Updated to v1.3.0, now works, problem was present  in v1.2.0 didn't even notice there was another release 1 hour after I downloaded it. Thanks keep up the good work
