### ISSUE TITLE
My card has 8GB of VRAM, but log says "Using 4GB of VRAM"

### ISSUE THREAD

**Issue by spitfire** [yamashi/PerformanceOverhaulCyberpunk#18]
My card has 8GB of VRAM, but log says
`[2020-12-14 13:24:14.552] [info] 		Using 4GB of VRAM`
is this normal?

**Comment by yamashi** [comment]
Fixed in 0.5.2

**Comment by spitfire** [comment]
Wow, thanks. Is it normal the amount of VRAM is set to less (7GB for me )than the actual amount the card has?
Why is both RAM and VRAM mentioned in the logs after I exit the game, and how can I check if it's really applied?
