### ISSUE TITLE
Async on 1.05

### ISSUE THREAD

**Issue by tombon12** [yamashi/PerformanceOverhaulCyberpunk#181]
I'm not sure if this is true as I'm not very experienced with this stuff, but it seems like the async patch no longer works on 1.05,
I added an .ini file in the engine/config/platform/pc  folder that tells Async to be turned off.
I also opened the config.json from this mod and changed "disable_async_compute" to true as well as "dump_game_options" to true, to see if the Async patch still works.
When I start the game, it doesnt seem like Async is off judging by the output of the game options:

```
[2020-12-20 20:01:24.316] [info] Rendering/AsyncCompute/RaytraceASBuild = true
[2020-12-20 20:01:24.316] [info] Rendering/AsyncCompute/Enable = true
[2020-12-20 20:01:24.316] [info] Rendering/AsyncCompute/HairClears = false
[2020-12-20 20:01:24.316] [info] Rendering/AsyncCompute/SSAO = true
[2020-12-20 20:01:24.316] [info] Rendering/AsyncCompute/LutGeneration = true
[2020-12-20 20:01:24.316] [info] Rendering/AsyncCompute/DynamicTexture = true
[2020-12-20 20:01:24.316] [info] Rendering/AsyncCompute/FlattenNormals = true
[2020-12-20 20:01:24.316] [info] Rendering/AsyncCompute/BuildDepthChain = true
[2020-12-20 20:01:24.316] [info] WaterSimulation/UseAsyncComputeFFT = true
```

I also included the entire log just in case there could be something usefull in there :)
[cyber_engine_tweaks.log](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5721363/cyber_engine_tweaks.log)

**Comment by emoose** [comment]
The setting values that CET dumps into the log file are the default ones baked into the EXE, as we dump the settings when they're first inited by the game, before any INI has been read/CET patch has been applied. 

Maybe worth mentioning on the wiki that only defaults are displayed. (I was also thinking it'd be nice to have a console command for dumping the values at runtime after the INI/CET stuff has loaded, now we have a Lua console I guess that should be pretty easy to add, will have to look into it soon)

**Comment by NielsGx** [comment]
tbh I don't even have a 1fps diff on a Ryzen 7 3700x + GTX 1060 6Gb, so hard gpu bottleneck..
Tried with this and also with ini edit and all. Loaded a save and checked fps in the same area, no difference whatsoever

**Comment by tombon12** [comment]
> The setting values that CET dumps into the log file are the default ones baked into the EXE, as we dump the settings when they're first inited by the game, before any INI has been read/CET patch has been applied, any changes won't be reflected in that dump atm since it was mostly only meant for giving us a way to create a list of all the settings the game uses.
> 
> Can see how that could be misleading though, maybe worth emphasising on the wiki that only defaults are displayed. (I was also thinking it'd be nice to have a console command for dumping the values at runtime after the INI/CET stuff has loaded, so we can see what current values are, now we have a Lua console I guess that shouldn't be too hard to add, will have to look into it soon)

Thanks for the clarification! didn't know those values were just the default settings
guess this wasn't an issue after all 👍
