### ISSUE TITLE
selectable key-binding for console

### ISSUE THREAD

**Issue by huginactual** [yamashi/PerformanceOverhaulCyberpunk#184]
I am unable to use the console as my laptop does not have an End key.  Would it be possible to add a feature to allow a user to define their own key-binding or a secondary console key?

**Comment by emoose** [comment]
It has it already, after running with CET once the config.json will have a `console_key` entry added to it, AFAIK the value for that needs to be a VK number, http://www.kbdedit.com/manual/low_level_vk_list.html has a list of them, you might need to convert the hex number to decimal first though.
