### ISSUE TITLE
game.addtoinventory() returns "attempt to index A nil value (global "game")

### ISSUE THREAD

**Issue by xunknxwnx** [yamashi/PerformanceOverhaulCyberpunk#185]
basically what the title says. i used the correct syntax ( game.addtoinventory("items.item", count) ) and nothing but an error. any idea how to fix?

edit: turned on debug, came back with this: ``[SendEventToDefaultPS] Unable to send event, there is no presistent state on that entity entEntityID[ hash:10179288 ]``

**Comment by yamashi** [comment]
This is case sensitive.

**Comment by Starlights-Smile** [comment]
@xunknxwnx - like Yamashi said, it is case sensitive. That said, I managed to format a list of items for the Game.AddToInventory("Items.Item", count) strand. If you'll find it helpful, here is a link to the google drive: https://docs.google.com/spreadsheets/d/1CCOmY__uhYhpRixs3XizqwUvx1LICqa2GrmyVpA2Nlc/edit?usp=sharing
