### ISSUE TITLE
Game don't start with newest version (proper VRAM detection)

### ISSUE THREAD

**Issue by Kichaa2** [yamashi/PerformanceOverhaulCyberpunk#19]
Trying to launch with GoG Launcher and .exe. Game shows in task manager, takes around 2100 KB and sits there doing nothing else. I waited couple of minutes but nothing happens.
I tried to change everything or one by one to true/false in config.json but game still won't start.

**Comment by yamashi** [comment]
Is there a performance_overhaul.log file created?

**Comment by MG4vQIs7Fv** [comment]
I am experiencing the exact same.
"performance_overhaul.log" is generated but remains empty at 0 bytes.

Info:
Performance Overhaul 1.5.1
GOG version 1.04 (Offline non Galaxy)
Windows 7 64 bit

The only modification I made was to "memory_pool_budgets.csv", but I reverted that to test.

**Comment by yamashi** [comment]
Does this happen with 0.5.1?

**Comment by danthespal** [comment]
for me with 0.5.2 i receive better performance on frame drops, they are less and it's sees my VRAM correctly.

**Comment by MG4vQIs7Fv** [comment]
Yes I was on v1.5.1. I just tried a reboot and I still have the same problem.
I noticed v1.5.2 was up and tried with that as well. Still the same result.

**Comment by yamashi** [comment]
Could be a windows 7 issue, though I don't have a windows 7 to try and debug this so unless someone external comes along and debugs it I don't think I will find a solution.

**Comment by yamashi** [comment]
I have read reports of people saying that they need to delete the files and then put them in the folder, that overwriting doesn't work for them.

**Comment by Kichaa2** [comment]
I deleted that files before puttting new ones. OS restarts doesn't help either.

**Comment by danthespal** [comment]
> I deleted that files before puttting new ones. OS restarts doesn't help either.

did you build them or download the release? if so I did the same building the dll in x86, but the game reads only x64

**Comment by Kichaa2** [comment]
Donwloaded from:
https://github.com/yamashi/PerformanceOverhaulCyberpunk/releases/tag/v0.5.2
Release.zip and unpacking it's content to "Cyberpunk 2077\bin\x64"

**Comment by MG4vQIs7Fv** [comment]
I am using the release version as well. I could try building it, but will take me some time as I haven't done that before.

I was messing around and it seems v0.2.1 does work for me. Even generates the log file and everything. But that's the highest version that works for me.

**Comment by yamashi** [comment]
I am just using DX11 to grab that information, I doubt it interferes with DX12 as it's released before they initialize the game engine.

**Comment by MG4vQIs7Fv** [comment]
I am very sorry, but I was being too optimistic when I said I could try building it myself. I don't have a clue where to even start. I have only ever done this on Linux with Build files and assumed it would be similar.

**Comment by yamashi** [comment]
You will need visual studio and xmake.
Open version.sln, build it for x64/release.
Then go in cyberpunk_patch, use the command `xmake project -k vs`, it will create a vs2019 folder, open the .sln file, build for x64/release.

You're all set!

**Comment by ErdeFB** [comment]
Could this be DX12 related? After the update, the game stopped working for me too. Thing is, I use a custom DX12 dll to translate DirectX in essence, to Vulkan. Yes, I know, I know, but just wanted to share since one person mentioned using this, a DX12 game on Win7, he must use the solution that shipped with the game with their custom d3d12.dll

**Comment by yamashi** [comment]
It could very well be that the DX12 translation layer causes the issue... Sadly I don't have much of a choice here, unless someone wants to upgrade to DX12 to see if that fixes the issue

**Comment by spitfire** [comment]
> Could this be DX12 related after all? After the update, the game stopped working for me too. Thing is, I use a custom DX12 dll to translate DirectX in essence, to Vulkan. Yes, I know, I know, but just wanted to share since one person mentioned using this, a DX12 game on Win7, he must use the solution that shipped with the game with their custom d3d12.dll

Do you mean DXVK? Is it performing better?

**Comment by ErdeFB** [comment]
> It could very well be that the DX12 translation layer causes the issue... Sadly I don't have much of a choice here, unless someone wants to upgrade to DX12 to see if that fixes the issue

Finally got on my PC and indeed for me the issue was the d3d12 -> Vulkan layer. Tested by deleting the related .dll files and then launching the game which worked normally.

> Do you mean DXVK? Is it performing better?

For me it does. Would I recommend it? No, for exactly reasons like this and other caveats.

**Comment by iperson** [comment]
Try going to GoG and doing repair for the game after removing this patch.

**Comment by ErdeFB** [comment]
Testing done. Methodology was as follows:

Test 1:
- Remove the game executable, all modfiles and Vulkan layer files.
- Verified file integrity with the tool provided by Valve in the Steam client
- Successfully ran the game to main menu

Test 2: 
- Installed the latest version of mod (debug menu)
- Successfully launched the game to main menu with default settings

performance_overhaul.log:
```
[2020-12-14 18:01:09.665] [info] Computed .text crc: D7E90F30
[2020-12-14 18:01:09.666] [info] 	Resolved to version: 1.04
[2020-12-14 18:01:09.696] [info] 	AMD SMT Patch: success
[2020-12-14 18:01:09.785] [info] 	Spectre patch: success
[2020-12-14 18:01:09.788] [info] 	Pool patch: success
[2020-12-14 18:01:09.794] [info] 	Virtual Input Patch: success
[2020-12-14 18:01:09.794] [info] 	Unlock menu patch: success
[2020-12-14 18:01:10.577] [info] 		Detected RAM: 15GB, using 11.0GB
[2020-12-14 18:01:10.767] [info] 		Using 7.8896484GB of VRAM
```

Test 3:
- Copied over dxgi.dll, dxvk_config.dll and d3d12.dll from Vulkan layer.
- Flatlines straight away before any graphics are shown

performance_overhaul.log:
```
[2020-12-14 18:06:09.658] [info] Computed .text crc: D7E90F30
[2020-12-14 18:06:09.659] [info] 	Resolved to version: 1.04
[2020-12-14 18:06:09.693] [info] 	AMD SMT Patch: success
[2020-12-14 18:06:09.806] [info] 	Spectre patch: success
[2020-12-14 18:06:09.808] [info] 	Pool patch: success
[2020-12-14 18:06:09.815] [info] 	Virtual Input Patch: success
[2020-12-14 18:06:09.815] [info] 	Unlock menu patch: success
[2020-12-14 18:06:10.591] [info] 		Detected RAM: 15GB, using 11.0GB
```

Cyberpunk2077_dxgi.log:
```
warn:  CreateDXGIFactory2: Ignoring flags
info:  Game: Cyberpunk2077.exe
info:  DXVK: v1.7.3-5-g495b2a09-async
info:  Built-in extension providers:
info:    Win32 WSI
info:    OpenVR
warn:  OpenVR: Failed to locate module
info:  Enabled instance extensions:
info:    VK_KHR_get_surface_capabilities2
info:    VK_KHR_surface
info:    VK_KHR_win32_surface
info:  GeForce GTX 1080:
info:    Driver: 460.79.0
info:    Vulkan: 1.2.155
info:    Memory Heap[0]: 
info:      Size: 8079 MiB
info:      Flags: 0x1
info:      Memory Type[7]: Property Flags = 0x1
info:    Memory Heap[1]: 
info:      Size: 8187 MiB
info:      Flags: 0x0
info:      Memory Type[0]: Property Flags = 0x0
info:      Memory Type[1]: Property Flags = 0x0
info:      Memory Type[2]: Property Flags = 0x0
info:      Memory Type[3]: Property Flags = 0x0
info:      Memory Type[4]: Property Flags = 0x0
info:      Memory Type[5]: Property Flags = 0x0
info:      Memory Type[6]: Property Flags = 0x0
info:      Memory Type[8]: Property Flags = 0x6
info:      Memory Type[9]: Property Flags = 0xe
info:    Memory Heap[2]: 
info:      Size: 246 MiB
info:      Flags: 0x1
info:      Memory Type[10]: Property Flags = 0x7
info:  DXGI: NvAPI workaround enabled, reporting AMD GPU
warn:  DxgiAdapter::QueryInterface: Unknown interface query
warn:  7abb6563-02bc-47c4-8ef9-acc4795edbcf
```

Let me know if you need anything in addition.

**Comment by MG4vQIs7Fv** [comment]
Unfortunately compilation failed during step 2 (xmake project -k vs).
It seems to be missing mhook (and later zlib). I'm not really sure why, but I wonder if they are being extracted to the wrong folders somehow.

```
  => install mhook 2.5.1 .. failed
if you want to get verbose errors, please see:
  -> C:\Users\Username\AppData\Local\.xmake\cache\packages\2012\m\mhook\2.5.1\installdir.failed\logs\install.txt
error: install failed!
```

`cannot runv(cmake -DCMAKE_INSTALL_PREFIX=C:\Users\Username\AppData\Local\.xmake\cache\packages\2012\m\mhook\2.5.1\source\mhook-2.5.1\build_B58178A0\install -DCMAKE_INSTALL_LIBDIR=C:\Users\Username\AppData\Local\.xmake\cache\packages\2012\m\mhook\2.5.1\source\mhook-2.5.1\build_B58178A0\install\lib -DBUILD_SHARED_LIBS=OFF -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 16 2019" -A x64 -DCMAKE_CXX_FLAGS_DEBUG=\"/MTd\" -DCMAKE_CXX_FLAGS_RELEASE=\"/MT\" -DCMAKE_C_FLAGS_DEBUG=\"/MTd\" -DCMAKE_C_FLAGS_RELEASE=\"/MT\" ..), No such file or directory`

On the directx .dll files:
They are located in the folder: "..\bin\x64\d3d12on7".
- d3d11on12.dll
- d3d12.dll

I'm not sure if that helps.

**Comment by yamashi** [comment]
Ah you probably also need to install cmake :(

**Comment by MG4vQIs7Fv** [comment]
That took me longer then I would have thought, but I managed to compile it and its working :-)
It had to change a few things and I have included my steps below. Thanks for your work on this yamashi!

- Install Visual Studio 2019 Community
- Install xmake (win64)
- Install cmake (win64)
- reboot system for PATHS to update

- Download a clone of the code and extract it
- Open "../version.sln" with Visual Studio
- Debug dropdown: Set to Release
- Win32 dropdown: set the x64
- Menu: Build, Build "version"
- Finished: "..\x64\Release\version.dll"

We need to make a repository for xmake.
- cmd: `xmake repo -u`

- Open "../cyberpunk_patch" folder in cmd
- cmd: `xmake project -k vsxmake`
- Allow package installs

For some reason I had to repeat this command, because mhook gave an error.

- Open "../cyberpunk_patch/vsxmake2019/cyberpunk_patch.sln" with Visual Studio
- Debug dropdown: Set to Release
- Win32 dropdown: set the x64
- Menu: Build, Build "perfomance_overhaul"

Visual Studio produced an error because it was ignoring the y/n prompt for the mhook download. I ran that command manually to grab it.
Open the "../cyberpunk_patch/vsxmake2019" folder in cmd.
- cmd: `xmake config -P . -p windows -m release -a x64 -o "build"`
- Repeat Build "perfomance_overhaul" if needed

**Comment by yamashi** [comment]
Thanks for sharing! Feel free to make a PR "BUILD.md" or something along those lines with the instructions ;)

**Comment by yochenhsieh** [comment]
I have this problem since v0.3.0. For me v0.2.1 still works for game to start. My operation system is Windows 7 SP1.

**Comment by waruqi** [comment]
> Ah you probably also need to install cmake :(

This is just because I forgot to add cmake dependency in the mhook package, I have fixed this package. https://github.com/xmake-io/xmake-repo/commit/aa4974fde92a27421cf439421527d365c818faa7

```console
xmake repo -u
```
