### ISSUE TITLE
Console Issue

### ISSUE THREAD

**Issue by MrStickyTissue** [yamashi/PerformanceOverhaulCyberpunk#195]
Im having an issue trying to get the Console to work. these are the errors ive recieved. i have tried it a few ways. Maybe im doing it wrong? 
lua: error: [string "game.inventory.addItem(Items..."]:1: attempt to index a nil value (global 'game')
lua: error: [string "player.inventory.addItem(Ite..."]:1: attempt to index a nil value (global 'player')
lua: error: [string "game.addtoinventory(Items.mo..."]:1: attempt to index a nil value (global 'game')

**Comment by MrStickyTissue** [comment]
did some searching and found the issue. must use it like this: Game.AddToInventory("Items.money", 1000)

**Comment by Bluefissure** [comment]
`Game.AddToInventory`
Lua is case-sensitive.
