### ISSUE TITLE
Vram and ram error

### ISSUE THREAD

**Issue by SpartanDraco** [yamashi/PerformanceOverhaulCyberpunk#20]
Since I stream this game I am interested in this mod since when I stream I need it to recognize and work as it should, the case is that I put the mod, it works but it recognizes 7 of Vram when it is a 2080 of 8124 mb I think I remember that It was the count and 15 GB of ram when I have 16 recognized by the system and reserved 200 megabytes, I do not know if it would affect me worse having the mod or not until I try it, but it is strange to me that it does not recognize the Vram and the ram well

**Comment by yamashi** [comment]
It's just a display rounding error, it will use the full ram.

**Comment by SpartanDraco** [comment]
In that case, shouldn't it be 8 GB? taking into account that it is rounded above 5 in this case it would be rounding to 8, no 7, right? And the 16 ram is also above 15.5, well if you tell me that you use it whole it works for me that I hope because it is strange recording if it goes worse I die XD

**Comment by yamashi** [comment]
No because for a CPU 0.9999 = 0, I should have said flooring error ^^

**Comment by SpartanDraco** [comment]
curious, but even so the GPU is above 8000 mb should be 8 and not 7 right?

**Comment by yamashi** [comment]
I used bit shift meaning I divide by 1024, not 1000 ;)

**Comment by SpartanDraco** [comment]
yes, well, just that my GPU is 8192 which is a computer multiplier of 1024 which should show 8 GB and not 7

**Comment by yamashi** [comment]
I am just using what DX11 returns: https://github.com/yamashi/PerformanceOverhaulCyberpunk/blob/59bb42d58d2edb566f0dd8fefdd9f3178505e60f/cyberpunk_patch/src/pool_patch.cpp#L70

It's just a calculation error in the display, the raw value returned by DX11 is what is passed to the game

**Comment by SpartanDraco** [comment]
As long as I use the 8 GB I do not care, several games have made it to me, including R6S at the beginning or GTAV but then they use it, the case is that it should show 8, if you assure me that it uses the 8 without failures it works for me, thanks equally for answering
