### ISSUE TITLE
VRAM detection value varies

### ISSUE THREAD

**Issue by gavin19** [yamashi/PerformanceOverhaulCyberpunk#21]
Using the latest patch (clean install, no overwrites) with VRAM size detection.

Started the game 8 times. The first time it properly allocated 8GB, but every time since it set it to 7GB.

If I manually set it to 8GB in `memory_pool_budgets.csv` it always uses 8GB.

If I set it back to 3GB in the csv, it reverts back to 7GB via the patch.

RAM usage is always set to 27GB (31GB detected).

The VRAM usage was always high pre-patch for me anyway. It didn't appear to be capped at 3GB. The biggest perf gain is from the noticeably higher CPU usage.

3600@4.2, 5700XT, 32GB RAM
GOG 1.04

**Comment by yamashi** [comment]
This is a rounding display error, it will use every byte of memory.
