### ISSUE TITLE
Someone Can explain

### ISSUE THREAD

**Issue by Zenek-Hastro** [yamashi/PerformanceOverhaulCyberpunk#22]
I'm sorry, i'm not so skilled, and i didn't understand how does it work (where i need to place those files?). If you can share more details about the installation, i will Pull a new readme with all instruction.

I will delete this ticket once i gain all information!

Thank you guys <3

**Comment by yamashi** [comment]
https://github.com/yamashi/PerformanceOverhaulCyberpunk/wiki
