### ISSUE TITLE
VRAM and RAM infos displayed in logs right after closing the game

### ISSUE THREAD

**Issue by Pipodi** [yamashi/PerformanceOverhaulCyberpunk#24]
Is it normal for these information to appear in logs right after closing the game?

```
[2020-12-14 15:28:13.719] [info] Computed .text crc: D7E90F30
[2020-12-14 15:28:13.719] [info] 	Resolved to version: 1.04
[2020-12-14 15:28:13.741] [info] 	AMD SMT Patch: success
[2020-12-14 15:28:13.813] [info] 	Spectre patch: success
[2020-12-14 15:28:13.814] [info] 	Pool patch: success
[2020-12-14 15:28:13.817] [info] 	Virtual Input Patch: success
[2020-12-14 15:28:14.255] [info] 		Detected RAM: 15GB, using 11GB
[2020-12-14 15:28:14.387] [info] 		Using 8GB of VRAM
 ```
From the timestamps I can see that the action happened when the patch is applied, but I reloaded the log file while in the game, but the last 2 rows weren't there.

i7 8770k, 16GB of RAM, RTX 2080.

**Comment by yamashi** [comment]
It's normal ;)

**Comment by JW-YiffPartySyncer** [comment]
Using a 3090.
Log says using 23GB but with GPU-Z i never observer more than 7-8GB VRAM usage

**Comment by yamashi** [comment]
This is a hint for the memory pool, not a hard allocation, it tells the game it can use 23 if needed.

**Comment by spitfire** [comment]
> Using a 3090.
> Log says using 23GB but with GPU-Z i never observer more than 7-8GB VRAM usage

I have 128GB of RAM, and it doesn't use most of it either;)

**Comment by andrhevictor** [comment]
@yamashi Shouldn't that be replacing the values in `memory pool budget.csv`? Is it safe to me manually change this?
![image](https://user-images.githubusercontent.com/26423766/102099926-3c25d800-3dff-11eb-819f-388ec92690a9.png)

**Comment by yamashi** [comment]
You can change the values yes, my method hooks the reader and when it finds a value that is not ideal it fixes it.
