### ISSUE TITLE
question: how to check if it is working

### ISSUE THREAD

**Issue by LadyViktoria** [yamashi/PerformanceOverhaulCyberpunk#26]
hi

how to check if it is working.
have 3090 and ryzen 5800x
still 45-50fps on 4k without rt and dlss
![image](https://user-images.githubusercontent.com/12160746/102098119-14e30100-3e27-11eb-974f-7f70e2ca818c.png)

**Comment by andrhevictor** [comment]
Step 5 in the [wiki](https://github.com/yamashi/PerformanceOverhaulCyberpunk/wiki#installation).

> (Optional) To check that everything works you can look at the logs in \<cyberpunk_install_path\>/bin/x64/performance_overhaul/performance_overhaul.log
