### ISSUE TITLE
Steam Overlay Disabled

### ISSUE THREAD

**Issue by CyberBug2069** [yamashi/PerformanceOverhaulCyberpunk#28]
Hi,
The patch is working perfectly fine. Kudos to Yamashi! However I'm facing a small problem. My steam overlay is disabled after installing the patch and I can't get the game to open it. I use the overlay to monitor my fps. Can you please help? 

Thanks in advance :)

**Comment by Zenek-Hastro** [comment]
I don't have a solution, but if you open another game, and the show-up the steam overlay, you can go inside the settings and then manage the fps counter! (is not a real fix, however, you can still display the fps, and use it meanwhile waiting for a fix)

**Comment by CyberBug2069** [comment]
Alright guys I'm real sorry for the trouble. I fixed it myself. Turns out running the game in administrator mode doesn't allow the overlay to work. If anyone else is having this same issue please try disabling it.
