### ISSUE TITLE
Support for Config file fixes

### ISSUE THREAD

**Issue by jonfairbanks** [yamashi/PerformanceOverhaulCyberpunk#3]
It was recently discovered that the Config file is sub-optimal. Could the fixes identified be integrated into this tool?

Info: https://www.reddit.com/r/cyberpunkgame/comments/kccabx/hey_cd_projekt_red_i_think_you_shipped_the_wrong/

Thanks!

**Comment by Jeremy-Laier** [comment]
Post is deleted, https://www.removeddit.com/r/cyberpunkgame/comments/kccabx/hey_cd_projekt_red_i_think_you_shipped_the_wrong/

for copy

**Comment by yamashi** [comment]
Is this the PoolCPU and PoolGPU settings ?
I gave it a shot and saw no improvements on my machine if someone who did use this trick and got a performance boost reads this I would appreciate your help with testing a patch for this.
Cheers!

**Comment by WhoSayIn** [comment]
As a data point, I haven't seen any difference whatsoever by changing that file from the reddit post.

**Comment by HtheChemist** [comment]
Noticed a slight improvement (5-7 fps) and what seems to be a slight increase in general texture quality.

**Comment by richardtatum** [comment]
As a further data point, I also saw no improvements by changing these config lines. Either to those recommended by the OP (16GB RAM, 8GB VRAM for my GPU) or both to 0 (which the text file suggests is auto-calc).

Ryzen 3700x, 32GB RAM, 5700XT.

FWIW: I monitored VRAM & RAM utilization and there was no difference in usage between any of these settings (default, recommended and zeroed). But pool allocation may not affect the overall usage, I am out of my depth here.

**Comment by alekmieczkowski** [comment]
I observed a performance increase when I updated config file.

Ryzen 3900x/RTX 3080/32GB RAM

Might be worth adding this in. Looks like worst case it does nothing, while best case it gives you a performance increase.

**Comment by grepwood** [comment]
Hi, not familiar with Windows development. Unix guy here.

Do I understand correctly, but does this mean there is no way of letting the exe know it can allocate as much resources as it wants, but we just need to raise the predefined bar?

**Comment by PSubutai** [comment]
As far as I can tell this does not work. You can make any edits to that file or even delete it and the game boots just fine and there are no changes. In fact, it makes no sense for it to work because OP of that Reddit thread didn't even uncomment the lines in the file for it to work. (Which by the way, it still doesn't.)

I also tried checking Process Explorer to see if the file is even used at all by the application and it seems it is not.

**Comment by badman27** [comment]
I went from 60fps to 90fps by modifying that config file. For reference, I have an RTX 3080, AMD 3800XT, and 64GB 3600MHz RAM. I had all setting set to their maximum level and DLSS set to Ultra Performance.

**Comment by null-dev** [comment]
For reference, no change here. Perhaps you could make a small installer that allows users to select the features they need?

**Comment by AberrantWolf** [comment]
> 
> 
> Hi, not familiar with Windows development. Unix guy here.
> 
> Do I understand correctly, but does this mean there is no way of letting the exe know it can allocate as much resources as it wants, but we just need to raise the predefined bar?

My best guess is that they set up a pool for custom memory management rather than relying on default OS memory handling. There are some potential advantages to this around efficiency of loading and maintaining memory, uploading data to the GPU, etc; especially if you can avoid having too many page faults in your access, which is perhaps more likely if you're allowing the OS to assign memory chunks -- I'm not familiar enough with OS memory management to know how likely, only that in theory such things might happen.

If the value is for pool size, then I would further assume that they ARE using default OS memory handling for everything else, and if your OS memory table is particularly fragmented or just not being handled well for whatever reason, I could understand some people seeing sometimes dramatic framerate improvements for when they're especially CPU-bound by things like page faults.

**Comment by alpharesearch** [comment]
I did the change and I have a reproduceable crash right after a save. Without the change no crash in that save. I have 32gb ram so i did 16gb and i have a 1080 ti so i did 11gb. Not 100% sure about the values I used, but looks right.

**Comment by alekmieczkowski** [comment]
> I did the change and I have a reproduceable crash right after a save. Without the change no crash in that save. I have 32gb ram so i did 16gb and i have a 1080 ti so i did 11gb. Not 100% sure about the values I used, but looks right.

Which 1080ti? Not all models have 11gb, so that may be your issue.

**Comment by alpharesearch** [comment]
> > I did the change and I have a reproduceable crash right after a save. Without the change no crash in that save. I have 32gb ram so i did 16gb and i have a 1080 ti so i did 11gb. Not 100% sure about the values I used, but looks right.
> 
> Which 1080ti? Not all models have 11gb, so that may be your issue.

Evga 1080 ti, and it states 11GB on the box.

**Comment by SEAPUNK** [comment]
Pretty sure there are different EVGA flavors of the same card. Mine is SC2.

**Comment by alpharesearch** [comment]
I bought the card when it came out, the box doesn't have any other designator. Is there a command I can run or any place where it shows?

**Comment by alekmieczkowski** [comment]
Its curious that you're getting crashes. What ram type & speed do you have? What CPU? Do you have game on HDD or SSD?

**Comment by AberrantWolf** [comment]
Might be worth trying with 10GB in case you haven't yet. If you have all the VRAM allocated and something needs to allocate something else for some reason, I could see that causing a GPU crash.

**Comment by grepwood** [comment]
This is bonkers. We're doing a memory manager's job here. I'm surprised CP2077 doesn't come with DOS4GW included.

**Comment by tirrorex** [comment]
I can confirm i saw an increase in performance allowing me to jump from high to ultra present with 1-2fps performance gain.
Cpu consumption jumped from around 30-36 to 36-64.
9900k, 2080ti

**Comment by federicotorrielli** [comment]
Tried setting both the PoolXXX to 0 (dinamically allocated) and saw some improvement on my system, at least 5 FPS recovered and more ram usage, but never reached high levels. Seems setting manually to max doesn't really reach the value setted, I have to take a better look at how the game really utilizes the config file. For now, I suggest to not implement this feature here, or setting it to 0.

**Comment by Violet-Vibes** [comment]
I'm on a i5-7600K, 16GB ram, 1060 6GB GFX. Noticed zero improvements using the config file no matter if i manually set it or set it to 0 and let it autodecide. 

Struggling to get above 30+ in night city on low (textures are at high)

**Comment by snailzrus** [comment]
Config file modification did nothing for me. Changed it to 32GB for CPU and 8GB for GPU, saw no change in FPS. Tried changing it down to 1GB for CPU and 512MB for GPU, same FPS as both the default config and the first change I tried. I even went so far as to just straight up delete the config file and try running the game to see if the file would be remade or if the game just wouldn't launch. It launched fine and ran identically to before the config file thing was even in question.

I'm, on the GOG version of the game. Doubt that means anything.

**Comment by yamashi** [comment]
I added this to the mod, it is enabled by default in v0.4.0, please let me know if it works for you as I don't get any performance change meaning I don't see if it actually works or not.

**Comment by DerTyan** [comment]
I experienced minor FPS gain (1-3 FPS), but the loading time seems to be reduced by a fair bit.
Running on a Ryzen 3600, 32GB RAM, RX 5700 XT and game is installed on a normal SATA SSD.

**Comment by Hellreaver** [comment]
> Is this the PoolCPU and PoolGPU settings ?
> I gave it a shot and saw no improvements on my machine if someone who did use this trick and got a performance boost reads this I would appreciate your help with testing a patch for this.
> Cheers!

I tried the fix in the reddit post. I have 32GB of ram, 8700k @ 5.1ghz and a 3070, I saw no improvement.
I still have low CPU&GPU usage, with a max fps of 100 on low (20% gpu usage) and a max 70% usage on ultra, with around 60-80fps.

**Comment by yamashi** [comment]
> 
> 
> > Is this the PoolCPU and PoolGPU settings ?
> > I gave it a shot and saw no improvements on my machine if someone who did use this trick and got a performance boost reads this I would appreciate your help with testing a patch for this.
> > Cheers!
> 
> I tried the fix in the reddit post. I have 32GB of ram, 8700k @ 5.1ghz and a 3070, I saw no improvement.
> I still have low CPU&GPU usage, with a max fps of 100 on low (20% gpu usage) and a max 70% usage on ultra, with around 60-80fps.
> 
> Edit: Actually now i'm confused - 100% cpu usage on low but 100fps. Before, it was 100fps and 20% usage. I'm not sure what's going on.

Could you try disabling the different patches in config.json to find the cause?

**Comment by Hellreaver** [comment]
> > > Is this the PoolCPU and PoolGPU settings ?
> > > I gave it a shot and saw no improvements on my machine if someone who did use this trick and got a performance boost reads this I would appreciate your help with testing a patch for this.
> > > Cheers!
> > 
> > 
> > I tried the fix in the reddit post. I have 32GB of ram, 8700k @ 5.1ghz and a 3070, I saw no improvement.
> > I still have low CPU&GPU usage, with a max fps of 100 on low (20% gpu usage) and a max 70% usage on ultra, with around 60-80fps.
> > Edit: Actually now i'm confused - 100% cpu usage on low but 100fps. Before, it was 100fps and 20% usage. I'm not sure what's going on.
> 
> Could you try disabling the different patches in config.json to find the cause?

Sure. I have to go to bed soon, but I really want to help fix this.

**Comment by yomisimie** [comment]
Tested on Ryzen 5 3600, RX Vega 64 with 8gb VRAM and 16gb or RAM, no noticeable difference with the latest version of the mod, i get this in my log:
`[2020-12-14 13:26:52.334] [info] 	Resolved to version: 1.04
[2020-12-14 13:26:52.356] [info] 	AMD SMT Patch: success
[2020-12-14 13:26:52.414] [info] 	Spectre patch: success
[2020-12-14 13:26:52.418] [info] 	Pool patch: success
[2020-12-14 13:26:52.420] [info] 	Virtual Input Patch: success
[2020-12-14 13:26:53.027] [info] 		Detected RAM: 15GB, using 11GB
[2020-12-14 13:26:53.027] [info] 		Using 4GB of VRAM
`

**Comment by yamashi** [comment]
It should now detect the amount of VRAM correctly.

**Comment by jonfairbanks** [comment]
Thanks for the quick patch. 🥰
