### ISSUE TITLE
Patch not working

### ISSUE THREAD

**Issue by Konnie1989** [yamashi/PerformanceOverhaulCyberpunk#34]
I followed the instructions on the wiki, but have noticed some issues.

In /bin/x64/ I get PerformanceOverhaulCyberpunk-master folder.

"You should see Cyberpunk2077.exe and version.dll in this directory, it means you did it correctly." Has version.dll but no .exe?
Which file/s are editable for the config shown on the wiki?
I have no logs either, assuming I have done something wrong??

Any help would be hugely appreciated! Keep up the great work.

**Comment by yamashi** [comment]
You have to download a Release, not the source code!

**Comment by Konnie1989** [comment]
Sorry, I am very new to this :(

Where may I find the release?
