### ISSUE TITLE
Patch not working

### ISSUE THREAD

**Issue by Pancholius** [yamashi/PerformanceOverhaulCyberpunk#37]
So the patch isn't doing anything. I unzip the files in x64, launch the game and the core usage is "wrong"
No log file is being created also. I've tried deleting all the patch files and even the exe to get a fresh one veryfing files on GOG and reinstalling the patch and still doesn't do anything.

Anyone knows what can be happening? Thanks.

**Comment by Zenek-Hastro** [comment]
i'm using version 0.5.2 and it works, try it !

**Comment by Pancholius** [comment]
I literally just tried that version like 10 minutes ago as I don't care about the debug feature and it still doesn't work. It's like the patch doesn't detect when the game launches. Thanks for the comment tho!

**Comment by Nobody616** [comment]
Hello,
it does exactly the same. 
no log file created.

**Comment by jdobruchowski** [comment]
Tried 0.5.2 and it did't work ,  my friend is doing this at the same time and his works

**Comment by Pancholius** [comment]
I've tried a few versions and only 0.2.1 works. It fixes the cpu usage issue and properly generates the log file. I mean, it's better than nothing but it doesn't include all the other features that were added afterwards. So I don't know in which version this issue was introduced, but 0.2.1 didn't have it.

**Comment by MG4vQIs7Fv** [comment]
This is the same as [this issue](https://github.com/yamashi/PerformanceOverhaulCyberpunk/issues/19).

**Comment by Pancholius** [comment]
That issue is about the game not starting. My game starts perfectly fine, but with no effects from the patch.

**Comment by XCanG** [comment]
@Pancholius can you confirm, that you have files in this path:

- Cyberpunk 2077\bin\x64\Cyberpunk2077.exe.plugins\performance_overhaul.dll
- Cyberpunk 2077\bin\x64\performance_overhaul\config.json
- Cyberpunk 2077\bin\x64\version.dll

Also which version you have: GOG, Steam, EGS?

**Comment by jdobruchowski** [comment]
For me it's GOG

**Comment by BinaryEx** [comment]
@XCanG I have the same problem, patch not work after version 0.2.1.
Game version GOG 1.04
verifying files didn't help

**Comment by Pancholius** [comment]
@XCanG  Yes, the files are in the right path. As I said, version 0.2.1 works fine.
GOG 1.04

**Comment by xvpower** [comment]
Same game will crash on start here is the log:

`[2020-12-14 14:35:03.094] [info] Computed .text crc: DD2E9477
[2020-12-14 14:35:03.094] [error] 	Unknown version, please update the mod
[2020-12-14 14:35:03.115] [info] 	AMD SMT Patch: success
[2020-12-14 14:35:03.115] [warning] 	Spectre patch: failed, unknown version
[2020-12-14 14:35:03.115] [info] 	Pool patch: failed
[2020-12-14 14:35:03.117] [info] 	Virtual Input Patch: success
`

**Comment by Pogogo007** [comment]
Just noticed the log file is now created in Cyberpunk 2077\bin\x64\performance_overhaul
Do check if it created for you guys

**Comment by Pancholius** [comment]
Just to clarify, the game launches fine, no errors, but the patch doesn't start and doesn´t create a log past version 0.2.1.

**Comment by Pogogo007** [comment]
> Just to clarify, the game launches fine, no errors, but the patch doesn't start and doesn´t create a log past version 0.2.1.

Have you checked for a log inside Cyberpunk 2077\bin\x64\performance_overhaul

**Comment by BinaryEx** [comment]
@Pogogo007 no log file in this folder

**Comment by Pancholius** [comment]
@Pogogo007 Just the config file in there.

**Comment by yobson1** [comment]
> Same game will crash on start here is the log:
> 
> `[2020-12-14 14:35:03.094] [info] Computed .text crc: DD2E9477 [2020-12-14 14:35:03.094] [error] Unknown version, please update the mod [2020-12-14 14:35:03.115] [info] AMD SMT Patch: success [2020-12-14 14:35:03.115] [warning] Spectre patch: failed, unknown version [2020-12-14 14:35:03.115] [info] Pool patch: failed [2020-12-14 14:35:03.117] [info] Virtual Input Patch: success `

Remove the old amd_patch.dll from Cyberpunk2077.exe.plugins

**Comment by outlaw420** [comment]
Anything newer than 0.2.1 doesn't work for me.
GOG 1.04
Windows 7... might be a win 7 thing then?

**Comment by Pancholius** [comment]
> Anything newer than 0.2.1 doesn't work for me.
> GOG 1.04
> Windows 7... might be a win 7 thing then?

I'm in Windows 10

**Comment by Dplanton** [comment]
Did you originally use the hex value edit fix for amd CPU’s? Try restoring the original exe values the installing this again perhaps?

**Comment by ThalonMook** [comment]
Patch will not work also for me.
GOG 1.04. Files in the right places.
Win 10 (2004)
Intel I7 4930K
GPU EVGA 1080TI

**Comment by Pancholius** [comment]
> Did you originally use the hex value edit fix for amd CPU’s? Try restoring the original exe values the installing this again perhaps?

The exe is untouched.

**Comment by sushank1** [comment]
If anyone is facing a problem where it doesn't install or create a log file do this

Download the latest visual studio package [https://support.microsoft.com/en-in/help/2977003/the-latest-supported-visual-c-downloads](url) install both the x64 and x86 version it will then install fine it doesn't matter if u have gog or steam version.

**Comment by Pancholius** [comment]
> If anyone is facing a problem where it doesn't install or create a log file do this
> 
> Download the latest visual studio package [https://support.microsoft.com/en-in/help/2977003/the-latest-supported-visual-c-downloads](url) install both the x64 and x86 version it will then install fine it doesn't matter if u have gog or steam version.

This was it, thanks!

**Comment by sushank1** [comment]
> > If anyone is facing a problem where it doesn't install or create a log file do this
> > Download the latest visual studio package [https://support.microsoft.com/en-in/help/2977003/the-latest-supported-visual-c-downloads](url) install both the x64 and x86 version it will then install fine it doesn't matter if u have gog or steam version.
> 
> This was it, thanks!

Enjoy 👍

**Comment by Nobody616** [comment]
Great! thanks!

**Comment by dwasss** [comment]
> If anyone is facing a problem where it doesn't install or create a log file do this
> 
> Download the latest visual studio package [https://support.microsoft.com/en-in/help/2977003/the-latest-supported-visual-c-downloads](url) install both the x64 and x86 version it will then install fine it doesn't matter if u have gog or steam version.

Might wanna update the Wiki with this info under Troubleshooting or as a requirement for this repo.

**Comment by yamashi** [comment]
Thanks for the info, it's added to the wiki.

**Comment by dwasss** [comment]
@sushank1 @yamashi silly question, but do you download the redist for Visual Studio 2015, 2017 and 2019 or an earlier version?

**Comment by sushank1** [comment]
> @sushank1 @yamashi silly question, but do you download the redist for Visual Studio 2015, 2017 and 2019 or for an earlier version?

2015, 2017 and 2019.
