### ISSUE TITLE
Typo in the Wiki

### ISSUE THREAD

**Issue by TheXenocide** [yamashi/PerformanceOverhaulCyberpunk#40]
Hey there, just noticed a typo in the wiki. I would have tried to edit myself and submit a pull request, but didn't see anything for it short of cloning the whole wiki repo (I've made 1 line doc edits in the github UI before, but maybe it only applies to source in the normal repo?) Anyway, the line reads as follows:

`You can repaid via GOG or Steam to revert your changes.`

I think "repaid" is probably meant to be "repair" and when I read it I thought it might confuse some people. Cool project, thanks for contributing!

**Comment by yamashi** [comment]
Thanks!
