### ISSUE TITLE
do you think you can decrease the draw distance?

### ISSUE THREAD

**Issue by gizi77** [yamashi/PerformanceOverhaulCyberpunk#41]

**Comment by CasualDev242** [comment]
This is something you can do yourself, do some research.
Here's a page with all available ini values: https://www.nexusmods.com/cyberpunk2077/mods/193
All credit goes to Inforgram1 for finding these values.

Anyway, there are lots of parameters you can tweak for performance.

For draw distance,
go into Cyberpunk 2077/engine/config/platform/pc/ and create a file names "user.ini".
Add the following inside:

[Streaming]
MaxStreamingDistance = 23170.251953

That is the default value listed. Decrease it as you wish.
There may be other more helpful factors at play, we're all still playing with what these values do.
