### ISSUE TITLE
Add option to use full RAM/VRAM for pool_patch

### ISSUE THREAD

**Issue by Trypticon8** [yamashi/PerformanceOverhaulCyberpunk#42]
After running the game with the latest plugin update and the mem pool fix enabled, I noticed a (slight) performance decrease and a general decrease in stability for my framerates as shown below. I had been using the edited .csv config sheet with my full amount of memory for both CPU and GPU as it had not caused any instability in the game for me, nor any PC crashes.

- With [PerfOverhaul](https://i.imgur.com/yyYbjaH.jpeg)'s memory fix 

- Mem fix disabled, using edited config set to my full amount of RAM/VRAM [here](https://i.imgur.com/CgYGJzo.jpeg)

Took a peek at the code for "pool_patch.cpp" and noticed on Line 60 that the patch subtracts 4GB from available memory as a crash precaution : `aSize = (gigsInstalled - 4) * kScaler;`. I'm not versed at all in C++ so I haven't tried to make a full edit of the file myself. I'd like to have a toggle that enables me to use the full amount of memory available in my system (with an added disclaimer should there be any crashing issues of course) if possible, as I'm currently having to disable the mem fix in the plugin and use the edited config instead. 

Also quick thanks for making this plugin, makes playing the game properly _far_ more convenient.

**Comment by yamashi** [comment]
Will think about it :)

**Comment by yobson1** [comment]
Perhaps a memory percentage option would be a better solution.

**Comment by Pogogo007** [comment]
Im actually gonna try making this right now. No promises tho
