### ISSUE TITLE
Uninstall help - No details

### ISSUE THREAD

**Issue by KingAnheuser** [yamashi/PerformanceOverhaulCyberpunk#49]
There are no details anywhere on how to uninstall this.
Any help would be appreciated.

**Comment by DrakeCaesar** [comment]
just delete the files you copied in

Cyberpunk2077.exe.plugins
performance_overhaul
LICENSE 
version.dll

**Comment by PhantomGamers** [comment]
technically just deleting or renaming version.dll is enough to disable the mod
