### ISSUE TITLE
Game crashes a lot on both 1.03 and 1.04 

### ISSUE THREAD

**Issue by Faxrijuf11** [yamashi/PerformanceOverhaulCyberpunk#51]
Game crashes every 10 minutes-1hour regardless of actions. Here is the crash log. Could you please determine the issue? Thanks, really appreciated!
[Cyberpunk2077-20201210-161337-7348-3404.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5693696/Cyberpunk2077-20201210-161337-7348-3404.zip)
[Cyberpunk2077-20201210-162630-11520-19296.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5693697/Cyberpunk2077-20201210-162630-11520-19296.zip)
[Cyberpunk2077-20201210-163843-19280-8860.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5693698/Cyberpunk2077-20201210-163843-19280-8860.zip)
[Cyberpunk2077-20201210-204005-14528-5036.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5693699/Cyberpunk2077-20201210-204005-14528-5036.zip)
[Cyberpunk2077-20201210-204634-7208-8272.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5693701/Cyberpunk2077-20201210-204634-7208-8272.zip)
[Cyberpunk2077-20201210-213908-3516-7528.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5693702/Cyberpunk2077-20201210-213908-3516-7528.zip)
[Cyberpunk2077-20201211-150357-12864-14804.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5693703/Cyberpunk2077-20201211-150357-12864-14804.zip)
[Cyberpunk2077-20201211-211734-13876-13564.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5693704/Cyberpunk2077-20201211-211734-13876-13564.zip)
[Cyberpunk2077-20201212-175131-16568-4272.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5693705/Cyberpunk2077-20201212-175131-16568-4272.zip)
[Cyberpunk2077-20201212-182731-1592-16000.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5693706/Cyberpunk2077-20201212-182731-1592-16000.zip)
[Cyberpunk2077-20201212-182748-14460-16104.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5693707/Cyberpunk2077-20201212-182748-14460-16104.zip)
[Cyberpunk2077-20201212-183532-7916-1276.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5693708/Cyberpunk2077-20201212-183532-7916-1276.zip)
[Cyberpunk2077-20201212-183658-19016-6592.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5693709/Cyberpunk2077-20201212-183658-19016-6592.zip)
[Cyberpunk2077-20201212-184457-2416-5664.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5693710/Cyberpunk2077-20201212-184457-2416-5664.zip)
[Cyberpunk2077-20201212-184558-5096-10952.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5693711/Cyberpunk2077-20201212-184558-5096-10952.zip)
[Cyberpunk2077-20201212-235721-18088-16220.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5693712/Cyberpunk2077-20201212-235721-18088-16220.zip)
[Cyberpunk2077-20201213-002124-16096-7140.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5693713/Cyberpunk2077-20201213-002124-16096-7140.zip)

**Comment by Kirides** [comment]
```
Error reason: Assert
Expression: result == archive::LoadingResult::SUCCESSFUL
Message: Failed to load archive E:\Games\Cyberpunk 2077\archive\pc\content\basegame_3_nightcity.archive, error 1, try regenerating archives!
File: e:\r6.patch0hotfix2\dev\src\common\resource\src\resourcegamedepot.cpp(499)
```

Try to verify the game integrity and disable your anti virus program. This sounds like the game either has no access to the file, or the file is damaged.
