### ISSUE TITLE
Docs for patches?

### ISSUE THREAD

**Issue by UditDey** [yamashi/PerformanceOverhaulCyberpunk#53]
I think it would be nice if the patches had documentation with explanations, for knowledge and transparency. For example, I can't seem to figure out what the spinlock patch is, and googling doesn't help. Just a suggestion.

**Comment by Saibamen** [comment]
https://en.wikipedia.org/wiki/Spinlock

**Comment by UditDey** [comment]
Yeah I know what a spinlock is...just don't know what this particular patch is doing in the context of the game

**Comment by yamashi** [comment]
It's disabled anyway but basically when running the game with a profiler I found this function to umbe using a lot of cpu time.
