### ISSUE TITLE
could u add this mod if possible

### ISSUE THREAD

**Issue by wjk199511140034** [yamashi/PerformanceOverhaulCyberpunk#6]
https://www.nexusmods.com/cyberpunk2077/mods/81?tab=posts
GTX1070 has get extra 10 fps with turning off all item associate with Rendering/AsyncComput/

**Comment by yamashi** [comment]
I think this would make more sense as a standalone considering it won't benefit everyone and having a mod that needs to be configured extensively to find the best settings for your use case is probably going to turn away less tech savy players.

**Comment by wjk199511140034** [comment]
> I think this would make more sense as a standalone considering it won't benefit everyone and having a mod that needs to be configured extensively to find the best settings for your use case is probably going to turn away less tech savy players.

In theory, it should work with all gtx10xx series (10xx series is not compatible with AsyncCompute?? ), My 1070 increased 10 , and my friend's 1060 get extra 6 approx, I also 'retweet' this method to another forum, more than 80% users reported that is effective

**Comment by Squall-Leonhart** [comment]
> 10xx series is not compatible with AsyncCompute??

False.

**Comment by CasualDev242** [comment]
> 
> 
> > 10xx series is not compatible with AsyncCompute??
> 
> False.

Not entirely, it has issues with it. Look up benchmarks regarding Async Compute performance on this series of gpu's and you should see a lot of hits come up.
I'm the one who originally reported this problem on Nexus. I definitely have seen a performance increase.

**Comment by CasualDev242** [comment]
@wjk199511140034 Although the fix wouldn't pertain to everyone, you could do a simple check to see if that series of checks is being used, and if so, disable Async Compute. It can be done in multiple ways, through ini value changes, and with the exe param "-gpuFlag noAsync".
NVAPI should give info on proper GPU detection: https://developer.nvidia.com/nvapi

**Comment by derplayer** [comment]
Did a standalone program, that allows to configure hidden settings in Cyberpunk 2077 without modifying the game executable.
Work great with PerformanceOverhaulCyberpunk at the side. Maybe it is useful for someone that reads this.

https://www.nexusmods.com/cyberpunk2077/mods/183
or
https://github.com/derplayer/ConfigOverhaulCyberpunk
