### ISSUE TITLE
CP 2077 Easy Installer

### ISSUE THREAD

**Issue by LittleZen** [yamashi/PerformanceOverhaulCyberpunk#60]
I know, the actual method is really easy, but many people are not really skilled with computer, so i've decided to create a EasyInstaller method in C#. Let me know if you wish use it, i can create a pull request ! 

How it works?
1) Just put the mod (and update) in the "Patch" folder
2) Open the EasyInstaller
3) Click on the button "Select Path" and follow the instruction

Some ScreenShot:
![image](https://user-images.githubusercontent.com/35767830/102233014-11677c80-3ef0-11eb-817a-32039294a015.png)
![image](https://user-images.githubusercontent.com/35767830/102233678-d0bc3300-3ef0-11eb-96b2-ef6c1b6c463d.png)
![image](https://user-images.githubusercontent.com/35767830/102233364-7c18b800-3ef0-11eb-9084-c02b2f296fad.png)
![image](https://user-images.githubusercontent.com/35767830/102233434-8d61c480-3ef0-11eb-8370-1b7edd6f7a63.png)

**Comment by Brokeos** [comment]
MetroFw is overkill I think, you should replace by your own components

**Comment by LittleZen** [comment]
I really prefer use it, cause have many useful tools! 

I've created the repository on my GitHub (and correctly refers it to this repository). You can now use it, or pass it to your friend for the easy installation ! 

https://bit.ly/2K7y7Hp

**Comment by LittleZen** [comment]
Working on a new release 

![image](https://user-images.githubusercontent.com/35767830/102253584-cd807180-3f07-11eb-961d-9a4e0a3a4de0.png)

**Comment by yamashi** [comment]
Feel free to make a PR with the easy installer.

**Comment by LittleZen** [comment]
Perfect, i am working for release the menu fixed, so the people can easy check or uncheck function directly on it. I will probably release it in 24h!
