### ISSUE TITLE
How to fix

### ISSUE THREAD

**Issue by noob188** [yamashi/PerformanceOverhaulCyberpunk#62]
![fixing-cyberpunk-2077-flatline](https://user-images.githubusercontent.com/76058054/102235210-1809ea00-3f18-11eb-8046-8510e47e3c49.jpg)

**Comment by BeauTaapken** [comment]
To know what the problem is, you should click on "What does this report contain?". This opens file explorer, where you should see a file called "stacktrace.txt". What does it say in that file?

**Comment by OLoKo64** [comment]
For me this happens every time I close the game, in your case the game is crashing during gameplay?
