### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by ZeroMaki** [yamashi/PerformanceOverhaulCyberpunk#64]
I'm running 1.03 tho (1.04 degraded my performance intensely) but the engine tweaks seem to not work at all.

**Comment by Zenek-Hastro** [comment]
As the developer said, this "mods", only work with 1.4 :/

**Comment by clementinise** [comment]
> [You are using a patch that is not supported (currently only 1.04 is supported for some patches).](https://github.com/yamashi/PerformanceOverhaulCyberpunk/wiki#it-says-unknown-version-and-patches-fail)

**Comment by ZeroMaki** [comment]
> > [You are using a patch that is not supported (currently only 1.04 is supported for some patches).](https://github.com/yamashi/PerformanceOverhaulCyberpunk/wiki#it-says-unknown-version-and-patches-fail)

thats under it saying unknown version or anything, it does absolutely nothing tho. But if it absolutely cannot work on 1.03 its pointless yes because 1.04 kills my fps and gives me stutters.

**Comment by moeinrahimi** [comment]
damn, i'm on 1.04 too
