### ISSUE TITLE
Installed the redistributable (wasn't originally installed) but still performance_overhaul.log file

### ISSUE THREAD

**Issue by metalshark** [yamashi/PerformanceOverhaulCyberpunk#65]
I am not seeing a
`<cyberpunk install path>/bin/x64/performance_overhaul/performance_overhaul.log`
file but am getting
`<cyberpunk install path>/bin/x64/plugins/cyber_engine_tweaks/cyber_engine_tweaks.log`
updated.

**Comment by AidanPrehatny** [comment]
this occurred for me as well, there are however logs within 
`<cyberpunk install path>/bin/x64/plugins/cyber_engine_tweaks/cyber_engine_tweaks.log`
might need to submit PR to update this

**Comment by yamashi** [comment]
Fixed the wiki, thanks for reporting!
