### ISSUE TITLE
Would it be possible to patch the .exe to apply the modifications?

### ISSUE THREAD

**Issue by DrakeCaesar** [yamashi/PerformanceOverhaulCyberpunk#66]
I'm playing on a platform where I can replace game files, but not add new ones. So I can for example replace memory_pool_budgets.csv, but I can't create new folders or files.
Could I patch the .exe by editing the binary data to apply some of the patches? Or does it have to be done on runtime?

**Comment by yamashi** [comment]
Most things have to be done at runtime sadly...
