### ISSUE TITLE
i7-7700k + ASUS GTX 1080Ti ROG Strix + 16GB RAM = 0% improvement

### ISSUE THREAD

**Issue by troncomputers** [yamashi/PerformanceOverhaulCyberpunk#67]
I have the same FPS (45 - 75) after this "patch" as before at 1080p... 😢🤷‍♂️

**Comment by Pogogo007** [comment]
As written on the nexus mod page "If you are GPU bound you will not see any performance increase on your average FPS but you should see less FPS drops."
