### ISSUE TITLE
Any idea why it may not be running in Proton?

### ISSUE THREAD

**Issue by okamidash** [yamashi/PerformanceOverhaulCyberpunk#69]
Heyo.
**Summary: No logfile is created for the mod. This implies the mod is not running** 

Feel free to close this if you like, but I'm trying to get this to run within Proton. 
It'd be useful to keep this open just to track if any other proton users are experiencing the same issues.

Steps to reproduce:
- Install `mesa-git`
- Install proton experimental
- Install Cyberpunk 2077
- Install the vc_redistx64.exe into the proton environment
- Launch game
- Observe that no performance_overhaul.log is created

Steps taken already:
- Deleted the .exe and revalidated
- Installed `vc_redistx64.exe`
- Deleted `bin/x64` and revalidated (as had installed the 'previous' version of the mod, and wanted to guarantee no artifacts left

**Comment by ArturVRSampaio** [comment]
yesterday i was using it to play with proton, with no issues at all. as soon as i go back home i will try the latest version, if it crashes i will report here =D

**Comment by ArturVRSampaio** [comment]
had your game already started without the mod?

**Comment by okamidash** [comment]
The game works fine. This is an issue for the mod itself, and whether it's running.

**Comment by ArturVRSampaio** [comment]
yeah, no idea... i will need to test it at home

**Comment by bundyo** [comment]
Doesn't seem to work for me too. There is no log output - the version.dll is being read, but that's it. The patch log doesn't get written.

**Comment by bundyo** [comment]
I've also installed vcrun2019 with protontricks, but still nothing.

**Comment by bundyo** [comment]
Okay, found the problem - when Proton/Wine encounter version.dll, they try to run the builtin one, which isn't the one from the plugin, thus fail to load it. Run protontricks --gui for your prefix, fire up winecfg and add `version` override and make it `native then builtin` to get the plugin to load.

**Comment by bundyo** [comment]
Heh, seems to detect memory wrong - CPU RAM: 77GB, using 38.0GB, while I only have 48, but still loads. Let me test how it works.

**Comment by bundyo** [comment]
Unfortunately I don't see any visual improvement with Proton Experimental.

**Comment by okamidash** [comment]
Just to confirm, is this `vcruntime140`?
