### ISSUE TITLE
Consider changing license to prevent paywalled redistribution

### ISSUE THREAD

**Issue by grepwood** [yamashi/PerformanceOverhaulCyberpunk#7]
This mod has ended up on nexusmods. Downloading anything from them has always been a pain in the ass, going back as early as my baby steps with TES3 Morrowind back in 200X. They are going the extra mile of banning usernames shared on bugmenot.com. You'll do them a favor of not increasing their storage costs, and everyone a massive - I'm using the term "paywall" very liberally, as having to register an account with nexusmods and solving their ridiculous captchas and waiting for download links to generate, just to be able to download anything, is a massive chore. Git is simple and doesn't care if you're a robot. There already are, and will be more people who will jump the opportunity to download the release files, post them behind paywalls and ask their peers to upvote their nexusmods link sky high.

**Comment by grepwood** [comment]
I don't understand the downvotes here. Maybe some opportunists chiming in ;)

Nexusmods is incredibly disadvantageous as a vehicle for redistribution of this project.
* The responsibility of coming back here once a blue moon to update the nexusmods submission rests on the random person responsible for uploading it there. That is, assuming they care, remember, and live.
* Here we can discuss everything in detail, because every release is associated with a git commit - a stadium of development of the entire project. This is not possible to the same degree of scrutiny on nexusmods.
* People can contribute here. Can't be done on nexusmods.
* If bus factor eats the original creator we can just fork it and the history and relation between the 2 projects stays, so that if theoretically this happens and there's a newer better fork that somehow isn't as well advertised on search engines, users can still figure out that there's a fork that's way ahead in commit count - on nexusmods everything is assumed to be original and such relations are inpalpable.

**Comment by wp2000x** [comment]
@grepwood true freedom is only when you have freedom to do mistakes.
When someone wants to use the paywalled nexusmods ecosystem them let em

**Comment by grepwood** [comment]
OK. Let's see what happens when someone puts a fork of this project coupled with a bitcoin miner on nexusmods.

**Comment by yamashi** [comment]
I am curious what license would work? If I am not mistaken any OSI license must allow paid redistribution ?

**Comment by EustaceCS** [comment]
Excuse me, @grepwood , why so harsh in the place so wrong?

MIT license under which this GIT repository currently is permitting redistribution - but only with inclusion of full MIT terms into redistribution copy.

If you have some personal grudge against NexusMods no Cyperpunk 2077 - report license violation there (because NexusMods copy does NOT include mentioned terms in its package) and call it a day.

This repository owner did great job with helping as many fellow players as possible. Why insisting on limiting redistribution at random?

**Comment by yamashi** [comment]
I am the one who posted on Nexus so I don't think reporting will make much sense ^^

**Comment by EustaceCS** [comment]
@yamashi , then toss https://github.com/yamashi/PerformanceOverhaulCyberpunk/blob/master/LICENSE into the archive just in case :)

I'm about https://www.nexusmods.com/cyberpunk2077/mods/107 .

>I am curious what license would work?

I believe, Creative Commons 4.0 Non-Commercial No Derivatives should do. Used it for one of my projects some time ago.

It was intended for books, etc. mainly - but as far as my knowledge allows to tell, it should do for code too.

**Comment by yamashi** [comment]
I think it's better for the future of modding for this game if I keep a permissive license, even if I were to change the license I don't have the means to enforce it if someone started selling the mod, so I will stick with MIT. It also wouldn't be fair to the people who found the issues.

**Comment by grepwood** [comment]
Owner of the repo has spoken and I respect their decision. The following is just an explanation of my POV for @yamashi and @EustaceCS. We all deserve honesty and transparency.
> Excuse me, @grepwood , why so harsh in the place so wrong?
> 
> MIT license under which this GIT repository currently is permitting redistribution - but only with inclusion of full MIT terms into redistribution copy.

MIT is permissive to a fault just like BSD - it won't protect its freedom and reputation, because defence denies the attacker the freedom to attack. You should know that, given you read the terms. GPLv3 prevents using and distributing the software in such fashion that obstructs access to the source and binaries. Nexusmods deploys exactly that. This isn't about money or selling the binaries, it's about setting up ridiculous obstacles in the way of downloading the mod and going as far as actively scanning bugmenot.com to prevent people from avoiding said obstacles.
> If you have some personal grudge against NexusMods no Cyperpunk 2077 - report license violation there (because NexusMods copy does NOT include mentioned terms in its package) and call it a day.

Thank you. I'll keep that in mind. This project is absolutely precious and it deserves protection.
> This repository owner did great job with helping as many fellow players as possible. Why insisting on limiting redistribution at random?

I perceived a threat to this project's good reputation in what's happening here https://old.reddit.com/r/cyberpunkgame/comments/kccabx/hey_cd_projekt_red_i_think_you_shipped_the_wrong/
What I see is someone posting a nexusmods link and using rhethoric that is meant to pander to non-technical audiences and attract them to a distribution channel known for demanding registrations and fabricating delays and making up arbitrary limitations of use, thus obstructing access to downloadable assets for no other real reason than the distribution channel's whim. Right after that, there's someone trying to redirect the audience's attention to this git repository. Honestly I think it's really fishy to have a nexusmods mirror if you already have a Github repo, because finding the releases page on Github is dead easy. When I was 12, I was computer illiterate and yet I had no problems downloading binaries for obscure sourceforge projects. Never got lost and landed in the code section until I knew what's a VCS. Sourceforge even had the appeal of being legitimate and trustworthy because it didn't have misleading download buttons like majorgeeks, filehippo, tucows and others, hence why I prefer VCS.

I'm old enough to remember how you couldn't download anything faster than 16KB/s from nexusmods, and how you had to wait for several minutes before you were queued for download, and how downloading something induced a timeout penalty during which you couldn't download anything more. What hasn't changed since then is that you still need to register an account, which in a network designed for exchange of information is a way of obstructing unrestricted access to unrestricted information. These ficticious obstacles sound more at home at a place where you renew a driver's license in person, not where you download files.

As I pondered further, it occurred to me that this can turn into a security breach. Call me paranoid. Maybe it's just work habits getting to me - at a previous workplace this would be definitely classified as a leak.

To add salt to injury, it's really inconvenient to download huge amounts of mods on not-Windows without paying for API access. I felt absolutely swarmed by the amount of nexusmods stuff OpenMW lists in their overhaul list. Easily 70GB. It doesn't help that their Mod Manager allows batch downloads, because it's written in .NET. I've been disappointed with .NET on Wine so many times that I don't even try anymore. It saves me plenty of time to assume it doesn't work and I'm almost always right about that.
> Never seen any captchas. Never waited for more than 5 (five) seconds. Maybe you'll provide some proofs for your words, okay?

I can get you a screenshot, sure. For now rest assured that if you log in to nexusmods from not-Windows and not-macOS with not-Chrome and not-Firefox, you'll be accused of being a robot. If you build your browser from source code, like every source-based distro user does, it will ignore the fact you're using a popular browser like Firefox.

**Comment by EustaceCS** [comment]
>For now rest assured that if you log in to nexusmods from not-Windows and not-macOS with not-Chrome and not-Firefox, you'll be accused of being a robot. If you build your browser from source code, like every source-based distro user does, it will ignore the fact you're using a popular browser like Firefox.

I'd suggest getting Cyberpunk 2077 on non-Windows non-MacOs systems which were built for compiling custom utility software from scratch first. Here's the link. https://www.gog.com/wishlist/games/cyberpunk_2077_on_linux

Starting pushing for appropriate modding support afterwards. Here's the link. https://github.com/Nexus-Mods/Vortex/issues/2862

And only then dealing with particular products security & licensing for such setups.

I'm using Nintendo Wii U as main gaming platform. But it doesn't mean that whole world should bend over in front of this fact. I accept disadvantages of my decision and I'm ready to switch to something more suitable once circumstances would demand.

**Comment by grepwood** [comment]
> I'd suggest getting Cyberpunk 2077 on non-Windows non-MacOs systems which were built for compiling custom utility software from scratch first. Here's the link. https://www.gog.com/wishlist/games/cyberpunk_2077_on_linux

Not sure about this. CDPR promised Linux ports of the Witcher series starting from Witcher 2. That game in particular got a really sloppy "port" which is just the game's exe and the entirety of Wine strapped into 1 executable. Further analysis showed that the entire Linux offering is single-threaded and does not support mods. Playing Witcher 2 is way better with Proton. Witcher 3 was meant to have a Linux port post-release, but it never materialized. Just to be safe and not get disappointed, I'm gonna wager CP2077 will never get a Linux port in any form. If I'm wrong, I'll just be happy I was wrong.
> Starting pushing for appropriate modding download support in such setups afterwards. Here's the link. [Nexus-Mods/Vortex#2862](https://github.com/Nexus-Mods/Vortex/issues/2862)

Before that materialized, I managed to service myself with my own Bash skills and a paid API key. I got what I wanted from nexusmods and my business is done with them.

**Comment by Simon-Steinmann** [comment]
@yamashi 
I just want to chime in quickly. 
https://www.nexusmods.com/cyberpunk2077/mods/107?tab=description
This mod posting has the guy's patreon and while it does not claim to be his creation, it gives no credit and links your patreon or anything like that. I just feel that this is wrong. You deserve credit. Do you have a patreon or any financial support links?

**Comment by yamashi** [comment]
@Simon-Steinmann this is my nexus account ^^

**Comment by Simon-Steinmann** [comment]
> 
> 
> @Simon-Steinmann this is my nexus account ^^

Oh okay nice :D
