### ISSUE TITLE
Graphic card not all use

### ISSUE THREAD

**Issue by Pluis3** [yamashi/PerformanceOverhaulCyberpunk#71]
I have a GTX 1050 on laptop and it's never using all the capacity it has. But, if I increase the quality it get a fps drop. I don't know if there's also for that a pourcentage lock or not but it seems stupid to me it never work at it best. Also I have an Intel graphic card that consume less energy but never use by the game. Does it could possible to make it possible to be both use and be able to put a pourcentage to the use of graphic card? Also I don't why but when I play a few  hours it gets a big drop of performance. I think I could be because it's overwhelming but I can't tell if it's because of the graphic card, ram, CPU and if it's cause by the boost. In the tasks manager the graphic card is approximately at 85°C so I don't know if it's too much on an laptop but I would not understand why it don't work well bc the ventilation looks to work really well.

**Comment by Hxxzii** [comment]
By capacity, do you mean VRAM or the GPU usage itself?

**Comment by Pluis3** [comment]
GPU. There is significant drop in performance because of its overheating, but it is strange. Most of the time it is at 50% utilization and sometimes it is at 100%. But I don't understand why it overheats at 50%.

**Comment by BeauTaapken** [comment]
Overheating doesn't go based on percentage used. It happens when the GPU is using voltage. When your GPU is getting higher clocks, it will take a more intensive load to get a higher GPU usage. I don't exactly know how you are checking this, but it is possible that when you are looking at the GPU usage at 100%, the clocks and voltage of the GPU are way lower, while when you are looking when it is at 50%, your GPU is drawing a lot more voltage, but also getting higher clocks. If you are using task manager to look at you GPU usage, i highly recommend using another tool. Taskmanager is known to show incorrect usages for GPU's. My old gpu was used for 1% while playing Horizon zero dawn, which isn't possible(used to have a 1080ti).

**Comment by Pluis3** [comment]
> Overheating doesn't go based on percentage used. It happens when the GPU is using voltage. When your GPU is getting higher clocks, it will take a more intensive load to get a higher GPU usage. I don't exactly know how you are checking this, but it is possible that when you are looking at the GPU usage at 100%, the clocks and voltage of the GPU are way lower, while when you are looking when it is at 50%, your GPU is drawing a lot more voltage, but also getting higher clocks. If you are using task manager to look at you GPU usage, i highly recommend using another tool. Taskmanager is known to show incorrect usages for GPU's. My old gpu was used for 1% while playing Horizon zero dawn, which isn't possible(used to have a 1080ti).

Do you can tell me some alternative to the task manager please?

**Comment by BeauTaapken** [comment]
> > Overheating doesn't go based on percentage used. It happens when the GPU is using voltage. When your GPU is getting higher clocks, it will take a more intensive load to get a higher GPU usage. I don't exactly know how you are checking this, but it is possible that when you are looking at the GPU usage at 100%, the clocks and voltage of the GPU are way lower, while when you are looking when it is at 50%, your GPU is drawing a lot more voltage, but also getting higher clocks. If you are using task manager to look at you GPU usage, i highly recommend using another tool. Taskmanager is known to show incorrect usages for GPU's. My old gpu was used for 1% while playing Horizon zero dawn, which isn't possible(used to have a 1080ti).
> 
> Do you can tell me some alternative to the task manager please?

Personally I use MSI afterburner. The primary use for the app is overclocking, but you can monitor a lot of things with it, like the GPU usage, GPU temperature, Core clock and Memory clock
