### ISSUE TITLE
Build Error commit 9078341a06b05e41236e9cd5d6d0314da7eb8eec

### ISSUE THREAD

**Issue by danthespal** [yamashi/PerformanceOverhaulCyberpunk#73]
I am getting this error, trying to xmake, its me or something is wrong?

`PS C:\WINDOWS\system32> cd E:\Git\PerformanceOverhaulCyberpunk
PS E:\Git\PerformanceOverhaulCyberpunk> xmake -y
[ 13%]: compiling.release src\avx_patch.cpp
error: ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:47:
stack traceback:
        [C]: in function 'error'
        @programdir\core\base\os.lua:789: in function 'raise'
        ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:47: in function 'co_start_named'
        @programdir\modules\private\async\runjobs.lua:180: in function <@programdir\modules\private\async\runjobs.lua:139>
        [C]: in function 'trycall'
        @programdir\core\base\scheduler.lua:423: in function 'co_group_begin'
        ...mdir\core\sandbox\modules\import\core\base\scheduler.lua:85: in function 'co_group_begin'
        @programdir\modules\private\async\runjobs.lua:139: in function 'runjobs'
        @programdir\actions\build\build.lua:222: in function 'build'
        @programdir\actions\build\main.lua:116: in function <@programdir\actions\build\main.lua:111>
        [C]: in function 'trycall'
        @programdir\core\sandbox\modules\try.lua:121: in function 'try'
        @programdir\actions\build\main.lua:110: in function <@programdir\actions\build\main.lua:83>
        [C]: in function 'load'
        @programdir\core\base\task.lua:519: in function 'run'
        @programdir\core\main.lua:282: in function 'cotask'
        @programdir\core\base\scheduler.lua:317: in function <@programdir\core\base\scheduler.lua:315>`

**Comment by yamashi** [comment]
This is odd, the CI passes so it's probably a local issue

**Comment by danthespal** [comment]
sorry, my fault i forgot I uninstall vs
