### ISSUE TITLE
Works but reduces performance?

### ISSUE THREAD

**Issue by cfortney92** [yamashi/PerformanceOverhaulCyberpunk#74]
This is a strange one - I followed the guide and I can see that it clearly fixed the SMT issue, because I went from seemingly 11 active threads before (that's odd in itself, no?) to 16 active threads on my 5800x afterward. But I've found across the board it dropped performance. I saved the game at a cut scene with the fix installed, steady at 41 FPS. I uninstalled the fix and loaded it back up, and FPS went back up to 52. Any thoughts on this?

**Comment by yamashi** [comment]
Can you try going in config.json and disable all of them and re enable one by one to know which one is causing your issue? This mod needs to be configured sometimes, it's not always the magic fix, every machine is unique so it can't be spot on every time

**Comment by cfortney92** [comment]
OK I'll give that a shot! For some context I'm running:

5800x (PBO enabled)
Gigabyte X570 Aorus Wifi
32GB G.Skill 3600 CL16
RTX 3070 FE (+130 mhz core, +900 mhz memory)
game is installed on a PCIE Gen 4 SSD

Before I discovered your GitHub page I had just found instructions to edit the Hex which I did the other night, and found it had the same results I'm getting here.

**Comment by yamashi** [comment]
You could disable amd smt in that case, the other changes should give a boost (sometimes hard to notice).

**Comment by cfortney92** [comment]
I'm going to give this some further extended testing. I've found no gains with the only difference being SMT clearly working via HWMonitor's report. And when I reported the FPS drop it seemed to occur after a few minutes rather than immediately, although I'm testing again now with everything enabled and so far haven't seen any drops...hmm...

**Comment by chendo** [comment]
Oddly enough, I have a 5800X, 32GB RAM, with a 3080 but on Low settings I get like 75fps max, and on Ultra with RT on (with some stuff like motion blur, grain, DOF turned off and some other settings lowered) I also get around 75fps, with the difference being the GPU usage is higher on Ultra.

The hex edit patch, pool config change didn't appear to solve the 75fps cap at Low which was how I was testing these patches cause I assume I should see an improvement there, but sadly did not improve performance for me there. I also tried the patches from this repo (with original exe and verified it was patching correctly in the logs) but it also does not appear to increase performance for me.

**Comment by PhantomGamers** [comment]
@chendo What kind of monitor do you have? It's not 75hz is it? (I'm thinking it might be because of vsync)

**Comment by chendo** [comment]
Good question, I have an ASUS VG27A 144hz running in G-SYNC mode, at 1440p. Windowed Fullscreen vs Fullscreen appears to make no difference. I have ensured that it's not being capped in settings, and the monitor's info panel is showing variable FPS. I don't have an issue in any other game that I currently play with the 75fps issue. I have also tried setting a max FPS in the game to see if it helps to no avail.

I also tried turning off SMT in the BIOS as well as lowering the number of cores active to 4 physical only, and it made no difference to FPS at Low.

**Comment by peter-dolkens** [comment]
@yamashi - I'm running a 5950x and 3080FE - the SMT patch REDUCES performance on my 5950x by approximately 10%.

I've been reading around, and seen similar results from many AMD users who have dual-CCD CPUs. single-CCD CPUs appear to benefit greatly from the SMT fix, but the higher-end CPUs are not.

I haven't looked too far into your patch just yet - but noticed you list the SMT patch in your list of fixes, and found this ticket to share the feedback on.

**Comment by PhantomGamers** [comment]
> I've been reading around, and seen similar results from many AMD users who have dual-CCD CPUs. single-CCD CPUs appear to benefit greatly from the SMT fix, but the higher-end CPUs are not.

Yes I have seen this as well, yet the 5800X only has one CCD so it's not consistent with that hm...

**Comment by peter-dolkens** [comment]
Good spot - I was thinking it was dual-CCD still

**Comment by aqxa1** [comment]
It's possibly due to the number of "real" cores (and how fast those cores are) rather than dual-CCD specifically. It might be that 8 strong cores is the minimum, and anything less than that needs SMT enabled.

**Comment by chendo** [comment]
Considering that effective CPU usage can go up but the actual performance doesn't improve performance makes it feel like a bad spinlock, which is why I thought this patch might fix the issue for me but sadly didn't seem to improve performance at Low

**Comment by Ed3n18** [comment]
I have an Intel System here and also experiencing 5-10fps lower with the patch. Tried exact same place with patch and without it.

9900K
32GB
RTX 3090

**Comment by PhantomGamers** [comment]
> I have an Intel System here and also experiencing 5-10fps lower with the patch. Tried exact same place with patch and without it.

Which patch? The SMT patch shouldn't do anything on an Intel system, it only affects AMD

**Comment by Ed3n18** [comment]
> > I have an Intel System here and also experiencing 5-10fps lower with the patch. Tried exact same place with patch and without it.
> 
> Which patch? The SMT patch shouldn't do anything on an Intel system, it only affects AMD

The entire patch/mod with all the fixes, copied the files, didn't change global.ini

**Comment by Mikecom32** [comment]
> Good question, I have an ASUS VG27A 144hz running in G-SYNC mode, at 1440p. Windowed Fullscreen vs Fullscreen appears to make no difference. I have ensured that it's not being capped in settings, and the monitor's info panel is showing variable FPS. I don't have an issue in any other game that I currently play with the 75fps issue. I have also tried setting a max FPS in the game to see if it helps to no avail.
> 
> I also tried turning off SMT in the BIOS as well as lowering the number of cores active to 4 physical only, and it made no difference to FPS at Low.
> 
> Measuring FPS is via MSI Afterburner and Nvidia's built in one.
> 
> When I'm in menus, I get ~105fps (but obviously not useful)

I have a similar issue - out of curiosity, what motherboard are you running?

**Comment by avrillapete** [comment]
> > > I have an Intel System here and also experiencing 5-10fps lower with the patch. Tried exact same place with patch and without it.
> > 
> > 
> > Which patch? The SMT patch shouldn't do anything on an Intel system, it only affects AMD
> 
> The entire patch/mod with all the fixes, copied the files, didn't change global.ini

I'm experiencing a 5-10 FPS drop as well with the mod installed, also on a 9900k. I tried turning on and off some of the settings in the mod config, like spectre fix and AVX fix(which the log said wasn't installed). Deleting the whole mod did not fix it, it's like the mod changed something that stuck.

**Comment by Ed3n18** [comment]
> > > > I have an Intel System here and also experiencing 5-10fps lower with the patch. Tried exact same place with patch and without it.
> > > 
> > > 
> > > Which patch? The SMT patch shouldn't do anything on an Intel system, it only affects AMD
> > 
> > 
> > The entire patch/mod with all the fixes, copied the files, didn't change global.ini
> 
> I'm experiencing a 5-10 FPS drop as well with the mod installed, also on a 9900k. I tried turning on and off some of the settings in the mod config, like spectre fix and AVX fix(which the log said wasn't installed). Deleting the whole mod did not fix it, it's like the mod changed something that stuck.

I deleted the mod and it went back to normal, compared it with a YT video benchmarking the game with a 3090. I can try future updates of the mod and see if it improves, but right now it makes it worse for me.

**Comment by yamashi** [comment]
The mod does a lot of things, it's the user's responsibility to tweak the mod settings to get the best out of the mod.

**Comment by chendo** [comment]
> I have a similar issue - out of curiosity, what motherboard are you running?

@Mikecom32 ASUS ROG B550-I, you?

**Comment by chendo** [comment]
Okay, it looks like my issue and potentially other people's issues is to do with ASUS' AI Suite 3 software. I tried to purge AI Suite 3 manually but it was an in-place reinstall of Windows 10 that resolved the issue for me. I'm able to get 144fps (monitor limit) at Low @ 1440p, and overall performance at my regular settings increased by ~10fps, and frametimes feels a lot smoother.

Post in question: https://forums.cdprojektred.com/index.php?threads/cant-get-over-60-65-fps-no-matter-what-resolution-or-settings-on-pc.11043734/page-10#post-12392714

**Comment by Mikecom32** [comment]
@chendo ASUS ROG X570-I here. I found the same thread yesterday and ended up removing AI Suite 3 and doing an in-place reinstall, which fixed the issue. I'm now regularly getting 100 fps at near ultra settings with raytracing. Glad you had the same experience.

@yamashi - Sorry for the ping, but it might be worth adding something about this issue in an FAQ or checking for the presence of the ASUS AI Suite 3 software and kicking a warning in the logs. This seems to be fairly wide-spread for anyone running AI Suite 3 with a modern ASUS board. Happy to do a PR for the former, but my C++ is too weak to do the latter.

**Comment by Ed3n18** [comment]
> @chendo ASUS ROG X570-I here. I found the same thread yesterday and ended up removing AI Suite 3 and doing an in-place reinstall, which fixed the issue. I'm now regularly getting 100 fps at near ultra settings with raytracing. Glad you had the same experience.
> 
> @yamashi - Sorry for the ping, but it might be worth adding something about this issue in an FAQ or checking for the presence of the ASUS AI Suite 3 software and kicking a warning in the logs. This seems to be fairly wide-spread for anyone running AI Suite 3 with a modern ASUS board. Happy to do a PR for the former, but my C++ is too weak to do the latter.

100fps, 1440p, Ultra settings, RTX all on and Ultra lighting? No DLSS?
