### ISSUE TITLE
0.8 removed pedestrians, no config options

### ISSUE THREAD

**Issue by MescalHeart** [yamashi/PerformanceOverhaulCyberpunk#79]
As title says, 0.8 removed all pedestrians on the street (massive performance boost, but not what I want) and it seems the options are missing from the config.json.

**Comment by thx4nothing** [comment]
Same problem. I tried to add the values to the config manually, but doesn't work, it removes them again.
Also the skip start menu patch doesn't seem to do anything.

**Comment by TheOne320** [comment]
> Same problem. I tried to add the values to the config manually, but doesn't work, it removes them again.
> Also the skip start menu patch doesn't seem to do anything.

The menu option currently in the config is to enable the debug menu. The two new options are missing.

**Comment by thx4nothing** [comment]
> 
> 
> > Same problem. I tried to add the values to the config manually, but doesn't work, it removes them again.
> > Also the skip start menu patch doesn't seem to do anything.
> 
> The menu option currently in the config is to enable the debug menu. The two new options are missing.

I know, I added "skip_start_menu" and "remove_pedestrians" myself (copied it from the source code). And then it behaved like I described.

**Comment by yamashi** [comment]
I might have shipped the wrong dll, working on it, sorry about that!

**Comment by MescalHeart** [comment]
Fixed in 0.8.1, thanks for fast turn around 👍
