### ISSUE TITLE
Start screen patch does not work

### ISSUE THREAD

**Issue by Areteic** [yamashi/PerformanceOverhaulCyberpunk#80]
Game version 1.04
PerformanceOverhauldCyberpunk version: 0.8.1

` "skip_start_menu": true ` does not skip anything, still have to press spacebar. Log reports patch was successful though

> [2020-12-16 18:06:06.955] [info] Computed .text crc: D7E90F30
> [2020-12-16 18:06:06.955] [info] 	Resolved to version: 1.04
> [2020-12-16 18:06:06.977] [info] 	AMD SMT Patch: success
> [2020-12-16 18:06:06.995] [info] 	Spectre patch: success
> [2020-12-16 18:06:07.000] [info] 	Pool patch: success
> [2020-12-16 18:06:07.004] [info] 	Virtual Input Patch: success
> [2020-12-16 18:06:07.058] [info] 	Start screen patch: success
> [2020-12-16 18:06:07.444] [info] 	CPU RAM: 31GB, using 19.0GB, fraction: 0.6
> [2020-12-16 18:06:07.599] [info] 	GPU VRAM: 9.8GB, using 9.8GB, fraction: 1.0
> 

Tried launching through steam and directly, same outcome.

On the other side `-skipStartScreen` in game launch options works but only for "good morning, Night City" video

**Comment by Areteic** [comment]
Disregard this issue, misunderstood what exactly is being skipped with this option, it is only for [BREACHING] screen

**Comment by jedahan** [comment]
maybe should be renamed 'skip BREACHING screen' for now
