### ISSUE TITLE
Memory report under Linux Proton Experimental off.

### ISSUE THREAD

**Issue by Jeoshua** [yamashi/PerformanceOverhaulCyberpunk#84]
I don't have access to Windows to verify this occurs in other situations, but the patch seems to work as advertised except for the fact that the log file shows this:
`
[2020-12-16 09:52:22.630] [info]        CPU RAM: 17GB, using 8.5GB, fraction: 0.5`

This is incorrect. I have 16GB of ram, as shown in free:

```
total        used        free      shared  buff/cache   available
Mem:       16373484     4694616     3908696      368228     7770172    10975728
Swap:       2097148        2816     2094332
```

Edit for formatting.

**Comment by florczakraf** [comment]
Looks pretty accurate to me because it also includes swap. The unit is probably GiB, not GB though. In my case its:

```
CPU RAM: 31GB, using 16.0GB, fraction: 0.5
```
Please note that the default unit for `free` is kibibyte
```
              total        used        free      shared  buff/cache   available
Mem:       16349036     8023912      362072      684648     7963052     7351432
Swap:      16723964        3072    16720892
```
which is roughly 31.54 GiB, rounded down to 31 in my case; in yours it's 17.61 rounded down to 17.

**Comment by yamashi** [comment]
You will have to open a ticket in the repo of the windows replacement you are using. I am using a standard winapi function that they apparently did not implement correctly...
