### ISSUE TITLE
REDString::RecursiveHash/Hash

### ISSUE THREAD

**Issue by iMoD1998** [yamashi/PerformanceOverhaulCyberpunk#86]
This isn't a custom hash algorithm. Its in fact FNV-1A based of the offset basis: 14695981039346656037ull
 and the prime 1099511628211ull.
 
 Wasnt sure if you was aware.

https://en.wikipedia.org/wiki/Fowler%E2%80%93Noll%E2%80%93Vo_hash_function

Heres some more info.

Can be implmented like so:

```cpp
static inline constexpr UINT64 NCFnv64(
	_In_   const char* String,
	_In_   bool        AsciiShouldLower = false,
	_In_   UINT64      CurrentHashValue = 0xCBF29CE484222325
)
{
	return ( ( String[ 0 ] == '\0' )
		? CurrentHashValue : NCFnv64( String + 1, AsciiShouldLower,
			( CurrentHashValue
				^ ( AsciiShouldLower
					? ( String[ 0 ] | ' ' ) : String[ 0 ] ) // simple to lower bitwise hack
				) * 0x00000100000001B3
		) );
}
```

**Comment by yamashi** [comment]
Yes this is known, was the same in Witcher3
