### ISSUE TITLE
Disable TAA also disables DLSS

### ISSUE THREAD

**Issue by ppmeis** [yamashi/PerformanceOverhaulCyberpunk#89]
There's any way to keep working DLSS if you disable TAA with this mod. Tested with latest release.

TAA OFF
![Cyberpunk 2077 Screenshot 2020 12 16 - 20 28 28 61](https://user-images.githubusercontent.com/4381277/102398660-de9cb180-3fdf-11eb-8923-a5bd55c60497.png)
Even with Ultra Performance DLSS image doesn't change.

TAA ON
![Cyberpunk 2077 Screenshot 2020 12 16 - 20 30 56 36](https://user-images.githubusercontent.com/4381277/102398664-e0667500-3fdf-11eb-8fed-cd098ac65d98.png)

**Comment by yamashi** [comment]
This is the expected behavior afaik.

**Comment by jedahan** [comment]
maybe add a comment in the feature that disabling TAA disables DLSS to hopefully reduce more people from opening similar issues
