### ISSUE TITLE
Disable TAA broke FPS and also visual

### ISSUE THREAD

**Issue by willatgit** [yamashi/PerformanceOverhaulCyberpunk#93]
Hi,

First of all, thank you for the tool.  it is almost perfect.

However, with the new version which offered to disable TAA, it cut my FPS from 90 to 42.

Also, after disable TAA is on, the picture quality is very bad.  I can see huge particle of noise like doing 1st pass rendering in Maya where it is just rendering a rough draft.... 

Please feel free to let me know what info you need.

Hope it is just a bug that disable TAA also disable post processing.  However, that still cannot tell me why it cut my FPS in half.

Anyway, I can provide all the info you need.  Just let me know what you need.

Thanks,

**Comment by PhantomGamers** [comment]
This is likely because disabling TAA also disables DLSS (#89). Nothing you can do about it, you have to choose between TAA being disabled or DLSS being enabled.

**Comment by rk-exxec** [comment]
That noise can come from the screen space reflections. Disabling them removed that issue for me. And there is still some reflections, just not the pretty ones.

**Comment by skeevy420** [comment]
Screen Space Reflections depends on information from TAA.  When disabling TAA, SSR should be disabled and Static CAS should be enabled and set around 75 or 85 to help with the FPS drops.

**Comment by willatgit** [comment]
I see.  Thank you all for the info.  I will keep tweaking my setting.
