### ISSUE TITLE
Unofficial Cyberpunk 2077 bugtracker 

### ISSUE THREAD

**Issue by dann1** [yamashi/PerformanceOverhaulCyberpunk#95]
Since this repo has gained a lot of popularity, almost 2k stars, and I can't find a platform to keep track of bugs. @yamashi do you think it would be a good idea to open a separate bug tracker for the game in another gh repo under your username? It would be a good way to track user feedback for current bugs, missing features, etc.

**Comment by yamashi** [comment]
That would be too much work, sorry
