### ISSUE TITLE
GOG integration not working anymore

### ISSUE THREAD

**Issue by badgab** [yamashi/PerformanceOverhaulCyberpunk#98]
Probably related to #87 and duplicate of #97 (since I take too much time to write this..)
GOG's overlay can't be summoned (shift+tab) since 0.9.
Can't take in-game screenshotsd with GOG's integration (F12).

* Tried to rollback to 0.7: overlay still not working
* Tried to remove all files: same, no overlay
* Tried restart GOG: no overlay
* Tried installing 0.10: no overlay
* Tried closing Discord: no overlay
* Tried another game on GOG: overlay is working

If it helps: First launch after installing 0.9, I got a crash at the seizure warning screen saying my AMD drivers weren't responding.

EDIT: 
- Adding duplicate issue (#97)
- Adding crashreport [Cyberpunk2077-20201216-213628-19468-25276.zip](https://github.com/yamashi/PerformanceOverhaulCyberpunk/files/5705826/Cyberpunk2077-20201216-213628-19468-25276.zip)

**Comment by gcsabai** [comment]
It may be related to GOG Galaxy update earlier today.
In addition to the patch, this update is the only thing that have changed since yesterday.

**Comment by yamashi** [comment]
If there is no overlay even without the mod, it's not the mod.
